In [ ]:
!pip install -U transformers accelerate peft bitsandbytes datasets tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.6.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Collecting peft
  Downloading peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.10.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.6.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 64.8 MB/s eta 0:00:00
Downloading peft-0.19.1-py3-none-any.whl (680 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.7/680.7 kB 35.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.1 MB/s eta 0:00:00
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 38.8 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 15.6 MB/s eta 0:00:00
Installing collected packages: pyarrow, bitsandbytes, datasets, transformers, peft
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: peft
    Found existing installation: peft 0.18.1
    Uninstalling peft-0.18.1:
      Successfully uninstalled peft-0.18.1
Successfully installed bitsandbytes-0.49.2 datasets-4.8.4 peft-0.19.1 pyarrow-24.0.0 transformers-5.6.0

In [ ]:
import os
import json
import math
import random
import re
import shutil
import torch
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm import tqdm
from datasets import Dataset

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    Trainer,
    TrainingArguments,
    DataCollatorForSeq2Seq,
    pipeline
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training
)

from google.colab import files

In [ ]:
ALPACA_TMPL = (
    "### Instruction:\n"
    "Answer as an endodontist using only the given context. "
    "Preserve exact clinical and endodontic keywords from the context whenever possible. "
    "Do not replace technical terms with general language. "
    "Use abbreviations such as NaOCl, EDTA, MTA exactly if they appear in the context.\n\n"
    "### Input:\n"
    "CONTEXT:\n{context}\n\n"
    "Question: {question}\n\n"
    "### Response:\n"
)

def format_for_training(context: str, question: str, answer: str) -> str:
    return ALPACA_TMPL.format(context=context, question=question) + answer

def format_for_inference(context: str, question: str) -> str:
    return ALPACA_TMPL.format(context=context, question=question)

In [ ]:
qa_model_id = "Qwen/Qwen2.5-1.5B-Instruct"

qa_tokenizer = AutoTokenizer.from_pretrained(
    qa_model_id,
    trust_remote_code=True
)

if qa_tokenizer.pad_token is None:
    qa_tokenizer.pad_token = qa_tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

qa_model = AutoModelForCausalLM.from_pretrained(
    qa_model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

qa_model.config.use_cache = False

print("Qwen QA generation modeli yüklendi.")

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Qwen QA generation modeli yüklendi.

In [ ]:
chunks_path = Path("/content/chunks (5).jsonl")
qa_output_path = Path("/content/raw_qa_dataset_qwen.jsonl")

rows = []
with chunks_path.open("r", encoding="utf-8") as f:
    for line in f:
        row = json.loads(line)
        if "text" in row and len(row["text"].strip()) > 250:
            rows.append(row)

print(f"Uygun chunk sayısı: {len(rows)}")
print(rows[0]["text"][:500])

Uygun chunk sayısı: 6584
Cohen’s Pathways of the Pulp TWELFTH EDITION EDITORS Louis H. Berman, DDS, FACD Clinical Associate Professor, Department of Endodontics, School of Dentistry, University of Maryland, Baltimore, Maryland Faculty, Albert Einstein Medical Center, Philadelphia, Pennsylvania Private Practice, Annapolis Endodontics, Annapolis, Maryland Diplomate, American Board of Endodontics Kenneth M. Hargreaves, DDS, PhD, FICD, FACD Professor and Chair, Department of Endodontics Professor, Departments of Pharmacolog

In [ ]:
qa_generator = pipeline(
    "text-generation",
    model=qa_model,
    tokenizer=qa_tokenizer
)

QA_GENERATION_PROMPT = """You are a world-class Endodontist.
Read the given text and produce exactly one question-answer pair.

STRICT FORMAT:
Question: ...
Answer: ...

Rules:
- The question must be answerable only from the given text.
- The answer must be short, clear, and highly technical.
- The answer must contain at least 2 important endodontic or clinical keywords copied from the text.
- Do not replace technical terms with simpler synonyms.
- If the text contains abbreviations such as EDTA, NaOCl, MTA, use them exactly.
- If you do not follow the format exactly, your answer is invalid.

Text:
{context}
"""

In [ ]:
def generate_qa(context: str):
    prompt = QA_GENERATION_PROMPT.format(context=context[:1000])

    outputs = qa_generator(
        prompt,
        max_new_tokens=140,
        do_sample=True,
        temperature=0.4,
        top_p=0.9,
        repetition_penalty=1.1,
        return_full_text=False
    )

    raw = outputs[0]["generated_text"].strip()
    raw = re.sub(r"\r\n", "\n", raw).strip()

    q_match = re.search(r"Question\s*:\s*(.+?)(?:\n|$)", raw, re.IGNORECASE | re.DOTALL)
    a_match = re.search(r"Answer\s*:\s*(.+)", raw, re.IGNORECASE | re.DOTALL)

    if not q_match or not a_match:
        lines = [line.strip() for line in raw.split("\n") if line.strip()]

        if len(lines) >= 2:
            question = lines[0]
            answer = " ".join(lines[1:])

            question = re.sub(r"^question\s*:?\s*", "", question, flags=re.IGNORECASE).strip()
            answer = re.sub(r"^answer\s*:?\s*", "", answer, flags=re.IGNORECASE).strip()
        else:
            return None
    else:
        question = q_match.group(1).strip()
        answer = a_match.group(1).strip()

    question = re.sub(r"^question\s*:?\s*", "", question, flags=re.IGNORECASE).strip()
    answer = re.sub(r"^answer\s*:?\s*", "", answer, flags=re.IGNORECASE).strip()

    if len(question) < 6 or len(answer) < 10:
        return None

    if len(question) > 300 or len(answer) > 1200:
        return None

    return {
        "context": context[:1000],
        "question": question,
        "answer": answer
    }


def save_jsonl(path, data):
    with open(path, "w", encoding="utf-8") as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")

In [ ]:
import torch
print("CUDA var mı?:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA var mı?: True
GPU: Tesla T4

In [ ]:
sample_size = min(2000, len(rows))
sampled_rows = random.sample(rows, sample_size)

raw_qa = []
for i, ch in enumerate(tqdm(sampled_rows, desc="QA generating with Qwen"), 1):
    item = generate_qa(ch["text"])
    if item:
        raw_qa.append(item)

    if i % 10 == 0:
        print(f"{i} işlendi | QA sayısı: {len(raw_qa)}")

print(f"Üretilen örnek sayısı: {len(raw_qa)}")
save_jsonl(qa_output_path, raw_qa)
print(f"Kaydedildi: {qa_output_path}")

QA generating with Qwen:   0%|          | 0/2000 [00:00<?, ?it/s][transformers] Passing `generation_config` together with generation-related arguments=({'temperature', 'repetition_penalty', 'do_sample', 'top_p', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 1/2000 [01:07<37:30:49, 67.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 2/2000 [01:39<25:46:47, 46.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 3/2000 [01:54<17:49:05, 32.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 4/2000 [02:08<13:51:12, 24.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 5/2000 [02:11<9:30:33, 17.16s/it] [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 6/2000 [02:25<8:49:29, 15.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 7/2000 [02:33<7:29:48, 13.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 8/2000 [02:49<7:57:19, 14.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 9/2000 [02:52<5:56:54, 10.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   0%|          | 10/2000 [03:00<5:25:25,  9.81s/it][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
[transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

10 işlendi | QA sayısı: 6

QA generating with Qwen:   1%|          | 11/2000 [03:04<4:27:10,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 12/2000 [03:06<3:27:27,  6.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 13/2000 [03:09<2:51:03,  5.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 14/2000 [03:12<2:34:59,  4.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 15/2000 [03:32<5:03:31,  9.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 16/2000 [03:45<5:43:54, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 17/2000 [03:48<4:31:22,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 18/2000 [03:55<4:12:27,  7.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 19/2000 [04:08<5:08:52,  9.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 20/2000 [04:21<5:43:54, 10.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

20 işlendi | QA sayısı: 12

QA generating with Qwen:   1%|          | 21/2000 [04:28<5:14:34,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 22/2000 [04:46<6:38:32, 12.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 23/2000 [05:00<6:50:26, 12.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|          | 24/2000 [05:13<6:56:47, 12.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|▏         | 25/2000 [05:26<7:03:11, 12.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|▏         | 26/2000 [05:34<6:16:08, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|▏         | 27/2000 [05:47<6:31:45, 11.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|▏         | 28/2000 [05:55<5:50:57, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   1%|▏         | 29/2000 [06:09<6:25:20, 11.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 30/2000 [06:23<6:44:53, 12.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

30 işlendi | QA sayısı: 19

QA generating with Qwen:   2%|▏         | 31/2000 [06:36<6:53:30, 12.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 32/2000 [06:44<6:01:56, 11.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 33/2000 [06:57<6:24:59, 11.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 34/2000 [07:10<6:39:06, 12.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 35/2000 [07:16<5:32:53, 10.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 36/2000 [07:29<6:06:44, 11.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 37/2000 [07:43<6:33:02, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 38/2000 [07:51<5:53:24, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 39/2000 [07:58<5:14:50,  9.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 40/2000 [08:11<5:49:53, 10.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

40 işlendi | QA sayısı: 23

QA generating with Qwen:   2%|▏         | 41/2000 [08:17<4:58:57,  9.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 42/2000 [08:27<5:05:41,  9.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 43/2000 [08:40<5:43:13, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 44/2000 [08:42<4:18:59,  7.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 45/2000 [08:52<4:38:09,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 46/2000 [09:05<5:22:47,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 47/2000 [09:09<4:28:43,  8.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 48/2000 [09:15<4:03:25,  7.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▏         | 49/2000 [09:28<4:57:05,  9.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   2%|▎         | 50/2000 [09:41<5:35:57, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

50 işlendi | QA sayısı: 29

QA generating with Qwen:   3%|▎         | 51/2000 [09:45<4:29:06,  8.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 52/2000 [09:47<3:35:14,  6.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 53/2000 [10:00<4:36:49,  8.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 54/2000 [10:14<5:21:25,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 55/2000 [10:27<5:58:49, 11.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 56/2000 [10:38<5:56:35, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 57/2000 [10:40<4:29:23,  8.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 58/2000 [10:44<3:47:06,  7.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 59/2000 [10:57<4:44:08,  8.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 60/2000 [11:04<4:30:31,  8.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

60 işlendi | QA sayısı: 36

QA generating with Qwen:   3%|▎         | 61/2000 [11:08<3:41:38,  6.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 62/2000 [11:21<4:41:39,  8.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 63/2000 [11:31<4:59:02,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 64/2000 [11:44<5:33:06, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 65/2000 [11:57<5:56:52, 11.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 66/2000 [12:03<5:07:35,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 67/2000 [12:16<5:40:30, 10.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 68/2000 [12:29<6:03:45, 11.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   3%|▎         | 69/2000 [12:42<6:22:30, 11.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▎         | 70/2000 [12:55<6:34:39, 12.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

70 işlendi | QA sayısı: 43

QA generating with Qwen:   4%|▎         | 71/2000 [13:00<5:22:02, 10.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▎         | 72/2000 [13:13<5:50:37, 10.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▎         | 73/2000 [13:26<6:10:44, 11.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▎         | 74/2000 [13:29<4:49:59,  9.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 75/2000 [13:43<5:31:59, 10.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 76/2000 [13:56<5:57:33, 11.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 77/2000 [14:09<6:15:50, 11.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 78/2000 [14:22<6:27:11, 12.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 79/2000 [14:28<5:30:10, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 80/2000 [14:41<5:53:32, 11.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

80 işlendi | QA sayısı: 48

QA generating with Qwen:   4%|▍         | 81/2000 [14:52<5:51:05, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 82/2000 [15:02<5:43:31, 10.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 83/2000 [15:04<4:25:48,  8.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 84/2000 [15:09<3:49:56,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 85/2000 [15:12<3:10:22,  5.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 86/2000 [15:17<3:02:05,  5.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 87/2000 [15:26<3:31:06,  6.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 88/2000 [15:32<3:23:43,  6.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 89/2000 [15:45<4:28:24,  8.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   4%|▍         | 90/2000 [15:58<5:08:37,  9.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

90 işlendi | QA sayısı: 55

QA generating with Qwen:   5%|▍         | 91/2000 [16:00<3:59:18,  7.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 92/2000 [16:13<4:53:19,  9.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 93/2000 [16:26<5:27:27, 10.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 94/2000 [16:39<5:53:01, 11.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 95/2000 [16:44<4:52:33,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 96/2000 [16:57<5:29:16, 10.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 97/2000 [17:03<4:47:05,  9.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 98/2000 [17:16<5:25:13, 10.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▍         | 99/2000 [17:29<5:52:03, 11.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 100/2000 [17:32<4:32:29,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

100 işlendi | QA sayısı: 63

QA generating with Qwen:   5%|▌         | 101/2000 [17:35<3:39:03,  6.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 102/2000 [17:48<4:40:53,  8.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 103/2000 [17:52<3:55:50,  7.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 104/2000 [18:06<4:51:00,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 105/2000 [18:20<5:34:52, 10.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 106/2000 [18:30<5:34:11, 10.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 107/2000 [18:44<6:05:18, 11.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 108/2000 [18:53<5:41:57, 10.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   5%|▌         | 109/2000 [19:07<6:06:58, 11.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 110/2000 [19:20<6:21:06, 12.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

110 işlendi | QA sayısı: 69

QA generating with Qwen:   6%|▌         | 111/2000 [19:34<6:36:01, 12.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 112/2000 [19:43<6:02:28, 11.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 113/2000 [19:56<6:21:08, 12.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 114/2000 [20:01<5:12:58,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 115/2000 [20:14<5:45:07, 10.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 116/2000 [20:18<4:34:24,  8.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 117/2000 [20:31<5:16:14, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 118/2000 [20:37<4:41:39,  8.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 119/2000 [20:51<5:20:56, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 120/2000 [21:04<5:48:18, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

120 işlendi | QA sayısı: 74

QA generating with Qwen:   6%|▌         | 121/2000 [21:12<5:23:04, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 122/2000 [21:30<6:34:06, 12.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 123/2000 [21:50<7:43:12, 14.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▌         | 124/2000 [22:03<7:26:55, 14.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 125/2000 [22:11<6:23:04, 12.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 126/2000 [22:19<5:43:37, 11.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 127/2000 [22:32<6:01:40, 11.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 128/2000 [22:36<4:55:42,  9.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 129/2000 [22:49<5:28:36, 10.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   6%|▋         | 130/2000 [23:02<5:50:40, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

130 işlendi | QA sayısı: 80

QA generating with Qwen:   7%|▋         | 131/2000 [23:16<6:10:32, 11.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 132/2000 [23:28<6:18:59, 12.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 133/2000 [23:32<4:54:12,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 134/2000 [23:34<3:45:42,  7.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 135/2000 [23:41<3:43:48,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 136/2000 [23:54<4:36:59,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 137/2000 [23:57<3:45:41,  7.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 138/2000 [24:10<4:37:34,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 139/2000 [24:22<5:08:53,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 140/2000 [24:35<5:32:14, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

140 işlendi | QA sayısı: 87

QA generating with Qwen:   7%|▋         | 141/2000 [24:38<4:18:33,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 142/2000 [24:50<4:58:29,  9.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 143/2000 [25:00<4:57:37,  9.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 144/2000 [25:03<3:54:24,  7.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 145/2000 [25:07<3:26:57,  6.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 146/2000 [25:20<4:23:39,  8.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 147/2000 [25:24<3:44:33,  7.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 148/2000 [25:38<4:40:04,  9.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   7%|▋         | 149/2000 [25:51<5:19:01, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 150/2000 [26:04<5:41:39, 11.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

150 işlendi | QA sayısı: 93

QA generating with Qwen:   8%|▊         | 151/2000 [26:17<5:57:55, 11.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 152/2000 [26:29<6:07:39, 11.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 153/2000 [26:42<6:14:57, 12.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 154/2000 [26:48<5:19:28, 10.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 155/2000 [26:52<4:15:49,  8.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 156/2000 [27:02<4:35:18,  8.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 157/2000 [27:06<3:44:19,  7.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 158/2000 [27:11<3:26:30,  6.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 159/2000 [27:15<3:03:38,  5.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 160/2000 [27:24<3:32:28,  6.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

160 işlendi | QA sayısı: 99

QA generating with Qwen:   8%|▊         | 161/2000 [27:37<4:25:09,  8.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 162/2000 [27:41<3:38:56,  7.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 163/2000 [27:54<4:30:33,  8.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 164/2000 [28:00<4:11:55,  8.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 165/2000 [28:13<4:54:43,  9.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 166/2000 [28:25<5:11:18, 10.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 167/2000 [28:30<4:26:15,  8.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 168/2000 [28:40<4:40:49,  9.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 169/2000 [28:43<3:41:53,  7.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   8%|▊         | 170/2000 [28:56<4:32:13,  8.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

170 işlendi | QA sayısı: 107

QA generating with Qwen:   9%|▊         | 171/2000 [29:09<5:07:03, 10.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▊         | 172/2000 [29:22<5:32:01, 10.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▊         | 173/2000 [29:34<5:48:52, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▊         | 174/2000 [29:46<5:52:10, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 175/2000 [29:59<6:00:30, 11.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 176/2000 [30:11<6:05:08, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 177/2000 [30:24<6:09:27, 12.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 178/2000 [30:37<6:17:17, 12.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 179/2000 [30:42<5:10:13, 10.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 180/2000 [30:54<5:33:00, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

180 işlendi | QA sayısı: 111

QA generating with Qwen:   9%|▉         | 181/2000 [31:07<5:50:09, 11.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 182/2000 [31:20<6:00:40, 11.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 183/2000 [31:33<6:06:46, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 184/2000 [31:38<5:08:41, 10.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 185/2000 [31:43<4:19:14,  8.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 186/2000 [31:56<4:57:03,  9.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 187/2000 [32:09<5:28:06, 10.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 188/2000 [32:22<5:47:03, 11.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:   9%|▉         | 189/2000 [32:31<5:23:41, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 190/2000 [32:34<4:13:52,  8.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

190 işlendi | QA sayısı: 116

QA generating with Qwen:  10%|▉         | 191/2000 [32:47<4:53:45,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 192/2000 [32:59<5:16:39, 10.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 193/2000 [33:02<4:08:35,  8.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 194/2000 [33:13<4:28:19,  8.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 195/2000 [33:25<4:56:23,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 196/2000 [33:37<5:19:36, 10.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 197/2000 [33:50<5:37:13, 11.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 198/2000 [34:02<5:49:49, 11.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|▉         | 199/2000 [34:09<5:04:02, 10.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 200/2000 [34:22<5:29:25, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

200 işlendi | QA sayısı: 119

QA generating with Qwen:  10%|█         | 201/2000 [34:35<5:44:55, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 202/2000 [34:47<5:55:33, 11.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 203/2000 [34:55<5:15:10, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 204/2000 [35:05<5:08:19, 10.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 205/2000 [35:08<4:02:43,  8.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 206/2000 [35:20<4:41:52,  9.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 207/2000 [35:33<5:11:49, 10.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 208/2000 [35:38<4:28:07,  8.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 209/2000 [35:41<3:29:59,  7.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  10%|█         | 210/2000 [35:54<4:21:52,  8.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

210 işlendi | QA sayısı: 126

QA generating with Qwen:  11%|█         | 211/2000 [36:07<4:58:41, 10.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 212/2000 [36:09<3:46:47,  7.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 213/2000 [36:13<3:19:19,  6.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 214/2000 [36:20<3:22:53,  6.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 215/2000 [36:25<3:01:14,  6.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 216/2000 [36:38<4:02:52,  8.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 217/2000 [36:51<4:44:48,  9.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 218/2000 [37:03<5:14:11, 10.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 219/2000 [37:16<5:35:16, 11.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 220/2000 [37:29<5:49:38, 11.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

220 işlendi | QA sayısı: 132

QA generating with Qwen:  11%|█         | 221/2000 [37:42<5:59:09, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 222/2000 [37:55<6:06:12, 12.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 223/2000 [37:57<4:30:32,  9.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█         | 224/2000 [38:01<3:46:22,  7.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█▏        | 225/2000 [38:14<4:33:05,  9.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█▏        | 226/2000 [38:17<3:38:15,  7.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█▏        | 227/2000 [38:29<4:23:32,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█▏        | 228/2000 [38:32<3:27:56,  7.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  11%|█▏        | 229/2000 [38:45<4:17:17,  8.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 230/2000 [38:57<4:45:16,  9.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

230 işlendi | QA sayısı: 139

QA generating with Qwen:  12%|█▏        | 231/2000 [39:04<4:20:14,  8.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 232/2000 [39:06<3:22:59,  6.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 233/2000 [39:19<4:15:13,  8.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 234/2000 [39:32<4:51:44,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 235/2000 [39:44<5:16:54, 10.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 236/2000 [39:58<5:42:20, 11.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 237/2000 [40:05<5:00:12, 10.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 238/2000 [40:08<3:56:38,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 239/2000 [40:14<3:41:06,  7.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 240/2000 [40:25<4:09:33,  8.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

240 işlendi | QA sayısı: 145

QA generating with Qwen:  12%|█▏        | 241/2000 [40:29<3:25:37,  7.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 242/2000 [40:35<3:24:41,  6.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 243/2000 [40:37<2:40:12,  5.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 244/2000 [40:41<2:24:44,  4.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 245/2000 [40:54<3:33:45,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 246/2000 [41:07<4:21:42,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 247/2000 [41:20<4:56:16, 10.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 248/2000 [41:27<4:35:20,  9.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▏        | 249/2000 [41:35<4:18:06,  8.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  12%|█▎        | 250/2000 [41:40<3:45:07,  7.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

250 işlendi | QA sayısı: 151

QA generating with Qwen:  13%|█▎        | 251/2000 [41:53<4:27:50,  9.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 252/2000 [42:02<4:28:04,  9.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 253/2000 [42:11<4:25:26,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 254/2000 [42:23<4:57:08, 10.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 255/2000 [42:36<5:18:37, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 256/2000 [42:39<4:08:10,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 257/2000 [42:52<4:45:02,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 258/2000 [43:05<5:10:35, 10.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 259/2000 [43:18<5:32:42, 11.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 260/2000 [43:31<5:47:58, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

260 işlendi | QA sayısı: 154

QA generating with Qwen:  13%|█▎        | 261/2000 [43:44<5:58:20, 12.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 262/2000 [43:47<4:34:33,  9.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 263/2000 [44:01<5:10:54, 10.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 264/2000 [44:14<5:34:27, 11.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 265/2000 [44:17<4:18:10,  8.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 266/2000 [44:31<4:58:04, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 267/2000 [44:38<4:36:20,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 268/2000 [44:44<3:59:38,  8.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  13%|█▎        | 269/2000 [44:57<4:44:09,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▎        | 270/2000 [45:11<5:16:10, 10.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

270 işlendi | QA sayısı: 162

QA generating with Qwen:  14%|█▎        | 271/2000 [45:24<5:38:25, 11.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▎        | 272/2000 [45:37<5:50:23, 12.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▎        | 273/2000 [45:51<5:59:18, 12.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▎        | 274/2000 [46:04<6:02:44, 12.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 275/2000 [46:06<4:32:04,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 276/2000 [46:12<4:05:40,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 277/2000 [46:25<4:41:00,  9.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 278/2000 [46:38<5:06:45, 10.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 279/2000 [46:51<5:26:19, 11.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 280/2000 [47:03<5:37:31, 11.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

280 işlendi | QA sayısı: 169

QA generating with Qwen:  14%|█▍        | 281/2000 [47:16<5:46:24, 12.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 282/2000 [47:19<4:25:48,  9.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 283/2000 [47:21<3:25:58,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 284/2000 [47:34<4:13:07,  8.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 285/2000 [47:36<3:11:46,  6.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 286/2000 [47:48<4:02:42,  8.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 287/2000 [48:01<4:40:07,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 288/2000 [48:10<4:32:23,  9.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 289/2000 [48:24<5:05:46, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  14%|█▍        | 290/2000 [48:37<5:26:33, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

290 işlendi | QA sayısı: 173

QA generating with Qwen:  15%|█▍        | 291/2000 [48:50<5:44:58, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 292/2000 [49:05<6:02:35, 12.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 293/2000 [49:07<4:37:58,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 294/2000 [49:20<4:59:45, 10.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 295/2000 [49:24<4:04:41,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 296/2000 [49:31<3:50:31,  8.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 297/2000 [49:35<3:16:17,  6.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 298/2000 [49:43<3:22:38,  7.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▍        | 299/2000 [49:56<4:16:14,  9.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 300/2000 [49:58<3:16:13,  6.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

300 işlendi | QA sayısı: 182

QA generating with Qwen:  15%|█▌        | 301/2000 [50:05<3:16:51,  6.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 302/2000 [50:08<2:41:35,  5.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 303/2000 [50:10<2:10:32,  4.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 304/2000 [50:14<2:09:47,  4.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 305/2000 [50:19<2:09:29,  4.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 306/2000 [50:32<3:22:53,  7.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 307/2000 [50:46<4:14:05,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 308/2000 [50:59<4:48:34, 10.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  15%|█▌        | 309/2000 [51:05<4:12:51,  8.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 310/2000 [51:18<4:47:46, 10.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

310 işlendi | QA sayısı: 188

QA generating with Qwen:  16%|█▌        | 311/2000 [51:31<5:13:09, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 312/2000 [51:44<5:29:07, 11.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 313/2000 [51:57<5:40:36, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 314/2000 [52:11<5:52:02, 12.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 315/2000 [52:24<5:56:26, 12.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 316/2000 [52:36<5:48:19, 12.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 317/2000 [52:43<5:03:11, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 318/2000 [52:45<3:51:59,  8.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 319/2000 [52:48<3:11:17,  6.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 320/2000 [53:01<4:03:24,  8.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

320 işlendi | QA sayısı: 195

QA generating with Qwen:  16%|█▌        | 321/2000 [53:14<4:37:19,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 322/2000 [53:19<3:51:58,  8.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 323/2000 [53:32<4:32:41,  9.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▌        | 324/2000 [53:35<3:40:04,  7.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 325/2000 [53:48<4:22:09,  9.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 326/2000 [54:01<4:52:46, 10.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 327/2000 [54:06<4:01:19,  8.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 328/2000 [54:10<3:24:35,  7.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 329/2000 [54:18<3:32:55,  7.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  16%|█▋        | 330/2000 [54:27<3:43:10,  8.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

330 işlendi | QA sayısı: 202

QA generating with Qwen:  17%|█▋        | 331/2000 [54:40<4:21:46,  9.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 332/2000 [54:53<4:48:30, 10.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 333/2000 [55:05<5:07:52, 11.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 334/2000 [55:18<5:21:18, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 335/2000 [55:31<5:31:12, 11.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 336/2000 [55:41<5:18:24, 11.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 337/2000 [55:54<5:29:34, 11.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 338/2000 [56:01<4:46:55, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 339/2000 [56:03<3:39:14,  7.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 340/2000 [56:07<3:05:03,  6.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

340 işlendi | QA sayısı: 210

QA generating with Qwen:  17%|█▋        | 341/2000 [56:10<2:39:23,  5.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 342/2000 [56:12<2:07:01,  4.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 343/2000 [56:25<3:16:22,  7.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 344/2000 [56:38<4:04:01,  8.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 345/2000 [56:43<3:28:35,  7.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 346/2000 [56:56<4:19:24,  9.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 347/2000 [56:59<3:26:07,  7.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 348/2000 [57:13<4:14:32,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  17%|█▋        | 349/2000 [57:27<4:53:15, 10.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 350/2000 [57:36<4:40:15, 10.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

350 işlendi | QA sayısı: 217

QA generating with Qwen:  18%|█▊        | 351/2000 [57:50<5:09:07, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 352/2000 [58:03<5:29:31, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 353/2000 [58:17<5:40:06, 12.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 354/2000 [58:20<4:27:51,  9.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 355/2000 [58:34<4:57:12, 10.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 356/2000 [58:47<5:21:16, 11.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 357/2000 [59:01<5:33:42, 12.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 358/2000 [59:03<4:13:23,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 359/2000 [59:17<4:47:18, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 360/2000 [59:30<5:10:22, 11.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

360 işlendi | QA sayısı: 223

QA generating with Qwen:  18%|█▊        | 361/2000 [59:35<4:20:48,  9.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 362/2000 [59:41<3:48:08,  8.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 363/2000 [59:54<4:28:47,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 364/2000 [59:59<3:51:12,  8.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 365/2000 [1:00:02<3:04:41,  6.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 366/2000 [1:00:08<2:56:21,  6.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 367/2000 [1:00:21<3:45:44,  8.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 368/2000 [1:00:23<2:59:45,  6.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 369/2000 [1:00:38<4:04:37,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  18%|█▊        | 370/2000 [1:00:51<4:42:00, 10.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

370 işlendi | QA sayısı: 230

QA generating with Qwen:  19%|█▊        | 371/2000 [1:00:57<3:59:30,  8.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▊        | 372/2000 [1:01:01<3:27:20,  7.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▊        | 373/2000 [1:01:15<4:12:06,  9.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▊        | 374/2000 [1:01:28<4:41:48, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 375/2000 [1:01:41<5:02:27, 11.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 376/2000 [1:01:53<5:16:06, 11.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 377/2000 [1:02:06<5:24:30, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 378/2000 [1:02:19<5:33:43, 12.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 379/2000 [1:02:22<4:14:53,  9.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 380/2000 [1:02:24<3:18:38,  7.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

380 işlendi | QA sayısı: 235

QA generating with Qwen:  19%|█▉        | 381/2000 [1:02:34<3:37:14,  8.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 382/2000 [1:02:36<2:46:14,  6.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 383/2000 [1:02:49<3:40:16,  8.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 384/2000 [1:02:51<2:52:03,  6.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 385/2000 [1:02:56<2:42:18,  6.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 386/2000 [1:03:09<3:37:15,  8.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 387/2000 [1:03:22<4:15:18,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 388/2000 [1:03:28<3:49:20,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  19%|█▉        | 389/2000 [1:03:41<4:24:22,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 390/2000 [1:03:54<4:46:50, 10.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

390 işlendi | QA sayısı: 239

QA generating with Qwen:  20%|█▉        | 391/2000 [1:04:06<5:02:51, 11.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 392/2000 [1:04:09<3:51:09,  8.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 393/2000 [1:04:12<3:05:01,  6.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 394/2000 [1:04:21<3:22:14,  7.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 395/2000 [1:04:33<4:03:19,  9.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 396/2000 [1:04:46<4:29:53, 10.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 397/2000 [1:04:51<3:53:24,  8.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 398/2000 [1:04:57<3:28:29,  7.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|█▉        | 399/2000 [1:05:06<3:38:44,  8.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 400/2000 [1:05:12<3:18:56,  7.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

400 işlendi | QA sayısı: 246

QA generating with Qwen:  20%|██        | 401/2000 [1:05:25<4:01:23,  9.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 402/2000 [1:05:33<3:53:25,  8.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 403/2000 [1:05:36<3:08:37,  7.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 404/2000 [1:05:42<3:02:26,  6.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 405/2000 [1:05:49<2:58:50,  6.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 406/2000 [1:05:58<3:18:49,  7.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 407/2000 [1:06:11<4:00:42,  9.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 408/2000 [1:06:23<4:29:56, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 409/2000 [1:06:26<3:31:24,  7.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  20%|██        | 410/2000 [1:06:39<4:09:31,  9.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

410 işlendi | QA sayısı: 253

QA generating with Qwen:  21%|██        | 411/2000 [1:06:52<4:35:35, 10.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 412/2000 [1:06:56<3:42:55,  8.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 413/2000 [1:07:08<4:17:20,  9.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 414/2000 [1:07:11<3:21:13,  7.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 415/2000 [1:07:24<4:01:39,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 416/2000 [1:07:27<3:12:04,  7.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 417/2000 [1:07:40<3:56:13,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 418/2000 [1:07:43<3:12:42,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 419/2000 [1:07:49<3:05:05,  7.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 420/2000 [1:07:56<3:04:56,  7.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

420 işlendi | QA sayısı: 260

QA generating with Qwen:  21%|██        | 421/2000 [1:08:08<3:39:29,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 422/2000 [1:08:21<4:14:03,  9.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 423/2000 [1:08:33<4:37:37, 10.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██        | 424/2000 [1:08:36<3:36:42,  8.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██▏       | 425/2000 [1:08:49<4:10:31,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██▏       | 426/2000 [1:09:01<4:35:20, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██▏       | 427/2000 [1:09:06<3:51:42,  8.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██▏       | 428/2000 [1:09:12<3:23:16,  7.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  21%|██▏       | 429/2000 [1:09:24<4:02:35,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 430/2000 [1:09:38<4:33:46, 10.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

430 işlendi | QA sayısı: 265

QA generating with Qwen:  22%|██▏       | 431/2000 [1:09:50<4:51:59, 11.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 432/2000 [1:09:55<3:58:56,  9.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 433/2000 [1:10:08<4:29:53, 10.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 434/2000 [1:10:21<4:49:41, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 435/2000 [1:10:24<3:47:55,  8.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 436/2000 [1:10:28<3:06:51,  7.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 437/2000 [1:10:36<3:19:35,  7.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 438/2000 [1:10:49<3:59:51,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 439/2000 [1:11:03<4:33:13, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 440/2000 [1:11:15<4:50:15, 11.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

440 işlendi | QA sayısı: 270

QA generating with Qwen:  22%|██▏       | 441/2000 [1:11:23<4:19:40,  9.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 442/2000 [1:11:36<4:42:41, 10.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 443/2000 [1:11:41<3:55:15,  9.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 444/2000 [1:11:53<4:23:50, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 445/2000 [1:11:55<3:21:48,  7.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 446/2000 [1:11:58<2:41:11,  6.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 447/2000 [1:12:11<3:32:37,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 448/2000 [1:12:24<4:06:37,  9.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▏       | 449/2000 [1:12:37<4:33:07, 10.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  22%|██▎       | 450/2000 [1:12:49<4:50:31, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

450 işlendi | QA sayısı: 275

QA generating with Qwen:  23%|██▎       | 451/2000 [1:13:02<5:01:57, 11.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 452/2000 [1:13:15<5:10:06, 12.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 453/2000 [1:13:28<5:15:36, 12.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 454/2000 [1:13:40<5:19:04, 12.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 455/2000 [1:13:53<5:22:21, 12.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 456/2000 [1:14:06<5:23:16, 12.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 457/2000 [1:14:08<4:06:13,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 458/2000 [1:14:12<3:15:53,  7.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 459/2000 [1:14:24<3:55:11,  9.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 460/2000 [1:14:27<3:08:38,  7.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

460 işlendi | QA sayısı: 280

QA generating with Qwen:  23%|██▎       | 461/2000 [1:14:40<3:50:58,  9.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 462/2000 [1:14:49<3:47:53,  8.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 463/2000 [1:15:03<4:26:10, 10.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 464/2000 [1:15:16<4:48:35, 11.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 465/2000 [1:15:29<4:57:48, 11.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 466/2000 [1:15:38<4:43:47, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 467/2000 [1:15:45<4:10:32,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 468/2000 [1:15:58<4:33:24, 10.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  23%|██▎       | 469/2000 [1:16:11<4:48:40, 11.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▎       | 470/2000 [1:16:24<5:01:52, 11.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

470 işlendi | QA sayısı: 283

QA generating with Qwen:  24%|██▎       | 471/2000 [1:16:26<3:47:10,  8.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▎       | 472/2000 [1:16:29<3:04:36,  7.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▎       | 473/2000 [1:16:42<3:44:22,  8.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▎       | 474/2000 [1:16:48<3:23:30,  8.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 475/2000 [1:17:01<4:03:27,  9.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 476/2000 [1:17:15<4:32:49, 10.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 477/2000 [1:17:16<3:24:32,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 478/2000 [1:17:25<3:25:48,  8.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 479/2000 [1:17:37<4:00:52,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 480/2000 [1:17:41<3:16:29,  7.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

480 işlendi | QA sayısı: 290

QA generating with Qwen:  24%|██▍       | 481/2000 [1:17:54<3:54:33,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 482/2000 [1:17:57<3:07:24,  7.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 483/2000 [1:18:01<2:39:20,  6.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 484/2000 [1:18:14<3:30:34,  8.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 485/2000 [1:18:16<2:43:07,  6.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 486/2000 [1:18:20<2:24:45,  5.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 487/2000 [1:18:26<2:26:39,  5.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 488/2000 [1:18:28<1:55:42,  4.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 489/2000 [1:18:41<2:59:41,  7.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  24%|██▍       | 490/2000 [1:18:54<3:43:22,  8.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

490 işlendi | QA sayısı: 299

QA generating with Qwen:  25%|██▍       | 491/2000 [1:18:58<3:10:03,  7.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 492/2000 [1:19:06<3:11:34,  7.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 493/2000 [1:19:09<2:36:19,  6.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 494/2000 [1:19:15<2:35:59,  6.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 495/2000 [1:19:27<3:23:11,  8.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 496/2000 [1:19:35<3:19:58,  7.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 497/2000 [1:19:48<3:55:33,  9.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 498/2000 [1:20:01<4:22:30, 10.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▍       | 499/2000 [1:20:13<4:32:02, 10.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 500/2000 [1:20:26<4:49:33, 11.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

500 işlendi | QA sayısı: 303

QA generating with Qwen:  25%|██▌       | 501/2000 [1:20:33<4:15:52, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 502/2000 [1:20:46<4:37:33, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 503/2000 [1:20:59<4:51:59, 11.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 504/2000 [1:21:13<5:06:10, 12.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 505/2000 [1:21:17<4:06:48,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 506/2000 [1:21:21<3:19:41,  8.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 507/2000 [1:21:34<3:56:49,  9.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 508/2000 [1:21:37<3:09:24,  7.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  25%|██▌       | 509/2000 [1:21:47<3:29:29,  8.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 510/2000 [1:21:58<3:46:38,  9.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

510 işlendi | QA sayısı: 308

QA generating with Qwen:  26%|██▌       | 511/2000 [1:22:11<4:13:09, 10.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 512/2000 [1:22:23<4:30:22, 10.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 513/2000 [1:22:33<4:21:48, 10.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 514/2000 [1:22:45<4:29:39, 10.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 515/2000 [1:22:57<4:42:48, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 516/2000 [1:23:03<3:58:15,  9.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 517/2000 [1:23:13<4:03:50,  9.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 518/2000 [1:23:20<3:40:38,  8.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 519/2000 [1:23:27<3:25:48,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 520/2000 [1:23:40<3:58:00,  9.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

520 işlendi | QA sayısı: 316

QA generating with Qwen:  26%|██▌       | 521/2000 [1:23:52<4:19:47, 10.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 522/2000 [1:24:05<4:36:36, 11.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 523/2000 [1:24:18<4:47:50, 11.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▌       | 524/2000 [1:24:31<4:55:25, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 525/2000 [1:24:36<4:03:31,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 526/2000 [1:24:39<3:12:22,  7.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 527/2000 [1:24:44<2:52:19,  7.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 528/2000 [1:24:57<3:34:56,  8.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 529/2000 [1:25:03<3:17:57,  8.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  26%|██▋       | 530/2000 [1:25:12<3:26:52,  8.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

530 işlendi | QA sayısı: 323

QA generating with Qwen:  27%|██▋       | 531/2000 [1:25:25<3:58:26,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 532/2000 [1:25:33<3:43:57,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 533/2000 [1:25:46<4:08:23, 10.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 534/2000 [1:25:58<4:28:18, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 535/2000 [1:26:07<4:07:20, 10.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 536/2000 [1:26:09<3:08:46,  7.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 537/2000 [1:26:21<3:45:16,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 538/2000 [1:26:34<4:11:17, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 539/2000 [1:26:47<4:28:52, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 540/2000 [1:26:50<3:27:42,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

540 işlendi | QA sayısı: 328

QA generating with Qwen:  27%|██▋       | 541/2000 [1:27:03<3:59:23,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 542/2000 [1:27:15<4:21:19, 10.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 543/2000 [1:27:28<4:36:04, 11.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 544/2000 [1:27:42<4:49:48, 11.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 545/2000 [1:27:53<4:49:13, 11.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 546/2000 [1:27:57<3:49:12,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 547/2000 [1:27:59<2:56:32,  7.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 548/2000 [1:28:13<3:40:37,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  27%|██▋       | 549/2000 [1:28:26<4:09:46, 10.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 550/2000 [1:28:32<3:35:15,  8.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

550 işlendi | QA sayısı: 331

QA generating with Qwen:  28%|██▊       | 551/2000 [1:28:37<3:09:53,  7.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 552/2000 [1:28:50<3:48:29,  9.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 553/2000 [1:28:52<2:56:18,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 554/2000 [1:29:04<3:30:09,  8.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 555/2000 [1:29:18<4:07:02, 10.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 556/2000 [1:29:24<3:37:05,  9.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 557/2000 [1:29:31<3:19:52,  8.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 558/2000 [1:29:44<3:54:31,  9.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 559/2000 [1:29:57<4:18:40, 10.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 560/2000 [1:30:00<3:20:57,  8.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

560 işlendi | QA sayısı: 338

QA generating with Qwen:  28%|██▊       | 561/2000 [1:30:13<3:54:32,  9.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 562/2000 [1:30:26<4:17:09, 10.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 563/2000 [1:30:39<4:35:20, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 564/2000 [1:30:43<3:35:24,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 565/2000 [1:30:55<4:03:15, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 566/2000 [1:31:09<4:23:57, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 567/2000 [1:31:22<4:37:43, 11.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 568/2000 [1:31:31<4:24:55, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 569/2000 [1:31:35<3:32:00,  8.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  28%|██▊       | 570/2000 [1:31:44<3:28:39,  8.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

570 işlendi | QA sayısı: 342

QA generating with Qwen:  29%|██▊       | 571/2000 [1:31:52<3:28:04,  8.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▊       | 572/2000 [1:32:05<3:56:43,  9.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▊       | 573/2000 [1:32:15<3:59:56, 10.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▊       | 574/2000 [1:32:19<3:15:09,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 575/2000 [1:32:33<3:54:37,  9.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 576/2000 [1:32:46<4:17:41, 10.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 577/2000 [1:32:59<4:34:29, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 578/2000 [1:33:13<4:44:43, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 579/2000 [1:33:25<4:50:46, 12.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 580/2000 [1:33:32<4:11:32, 10.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

580 işlendi | QA sayısı: 347

QA generating with Qwen:  29%|██▉       | 581/2000 [1:33:46<4:32:58, 11.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 582/2000 [1:33:58<4:39:47, 11.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 583/2000 [1:34:11<4:44:27, 12.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 584/2000 [1:34:24<4:52:17, 12.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 585/2000 [1:34:32<4:22:59, 11.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 586/2000 [1:34:36<3:30:40,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 587/2000 [1:34:46<3:39:24,  9.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 588/2000 [1:34:59<4:03:54, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  29%|██▉       | 589/2000 [1:35:07<3:48:56,  9.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 590/2000 [1:35:16<3:43:39,  9.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

590 işlendi | QA sayısı: 353

QA generating with Qwen:  30%|██▉       | 591/2000 [1:35:20<3:03:29,  7.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 592/2000 [1:35:25<2:38:14,  6.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 593/2000 [1:35:27<2:06:52,  5.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 594/2000 [1:35:33<2:09:47,  5.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 595/2000 [1:35:46<3:01:16,  7.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 596/2000 [1:35:49<2:27:41,  6.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 597/2000 [1:35:51<1:59:09,  5.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 598/2000 [1:36:03<2:52:29,  7.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|██▉       | 599/2000 [1:36:15<3:19:00,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 600/2000 [1:36:27<3:46:53,  9.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

600 işlendi | QA sayısı: 360

QA generating with Qwen:  30%|███       | 601/2000 [1:36:40<4:09:31, 10.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 602/2000 [1:36:53<4:22:30, 11.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 603/2000 [1:37:05<4:31:08, 11.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 604/2000 [1:37:18<4:41:40, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 605/2000 [1:37:31<4:45:51, 12.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 606/2000 [1:37:39<4:15:44, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 607/2000 [1:37:46<3:48:33,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 608/2000 [1:37:59<4:10:10, 10.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 609/2000 [1:38:12<4:25:38, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  30%|███       | 610/2000 [1:38:18<3:42:43,  9.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

610 işlendi | QA sayısı: 365

QA generating with Qwen:  31%|███       | 611/2000 [1:38:22<3:02:48,  7.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 612/2000 [1:38:24<2:27:57,  6.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 613/2000 [1:38:37<3:12:59,  8.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 614/2000 [1:38:50<3:43:20,  9.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 615/2000 [1:39:03<4:04:05, 10.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 616/2000 [1:39:08<3:24:42,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 617/2000 [1:39:20<3:51:03, 10.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 618/2000 [1:39:33<4:09:51, 10.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 619/2000 [1:39:39<3:36:20,  9.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 620/2000 [1:39:47<3:22:13,  8.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

620 işlendi | QA sayısı: 371

QA generating with Qwen:  31%|███       | 621/2000 [1:39:56<3:27:05,  9.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 622/2000 [1:40:01<2:58:23,  7.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 623/2000 [1:40:14<3:33:23,  9.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███       | 624/2000 [1:40:27<3:57:54, 10.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███▏      | 625/2000 [1:40:40<4:14:54, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███▏      | 626/2000 [1:40:52<4:25:42, 11.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███▏      | 627/2000 [1:41:05<4:33:04, 11.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███▏      | 628/2000 [1:41:14<4:14:58, 11.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  31%|███▏      | 629/2000 [1:41:17<3:14:44,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 630/2000 [1:41:30<3:46:08,  9.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

630 işlendi | QA sayısı: 377

QA generating with Qwen:  32%|███▏      | 631/2000 [1:41:40<3:47:42,  9.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 632/2000 [1:41:53<4:06:04, 10.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 633/2000 [1:41:56<3:16:46,  8.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 634/2000 [1:42:09<3:47:45, 10.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 635/2000 [1:42:23<4:08:24, 10.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 636/2000 [1:42:35<4:21:22, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 637/2000 [1:42:44<4:02:18, 10.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 638/2000 [1:42:57<4:18:15, 11.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 639/2000 [1:43:03<3:37:11,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 640/2000 [1:43:05<2:51:12,  7.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

640 işlendi | QA sayısı: 383

QA generating with Qwen:  32%|███▏      | 641/2000 [1:43:10<2:30:48,  6.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 642/2000 [1:43:13<2:07:06,  5.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 643/2000 [1:43:26<2:59:34,  7.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 644/2000 [1:43:39<3:32:15,  9.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 645/2000 [1:43:52<3:58:07, 10.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 646/2000 [1:43:55<3:05:58,  8.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 647/2000 [1:44:01<2:50:11,  7.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 648/2000 [1:44:05<2:26:55,  6.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▏      | 649/2000 [1:44:16<2:51:02,  7.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  32%|███▎      | 650/2000 [1:44:28<3:26:43,  9.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

650 işlendi | QA sayısı: 390

QA generating with Qwen:  33%|███▎      | 651/2000 [1:44:41<3:51:34, 10.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 652/2000 [1:44:44<3:01:09,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 653/2000 [1:44:51<2:50:23,  7.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 654/2000 [1:45:04<3:29:55,  9.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 655/2000 [1:45:18<3:58:30, 10.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 656/2000 [1:45:31<4:15:38, 11.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 657/2000 [1:45:39<3:53:13, 10.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 658/2000 [1:45:52<4:11:59, 11.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 659/2000 [1:46:00<3:49:52, 10.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 660/2000 [1:46:05<3:14:35,  8.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

660 işlendi | QA sayısı: 396

QA generating with Qwen:  33%|███▎      | 661/2000 [1:46:19<3:44:25, 10.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 662/2000 [1:46:32<4:06:08, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 663/2000 [1:46:37<3:24:25,  9.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 664/2000 [1:46:48<3:41:22,  9.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 665/2000 [1:46:51<2:49:44,  7.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 666/2000 [1:47:03<3:23:30,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 667/2000 [1:47:16<3:49:04, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 668/2000 [1:47:29<4:05:09, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  33%|███▎      | 669/2000 [1:47:35<3:31:32,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▎      | 670/2000 [1:47:48<3:52:40, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

670 işlendi | QA sayısı: 403

QA generating with Qwen:  34%|███▎      | 671/2000 [1:48:00<4:01:11, 10.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▎      | 672/2000 [1:48:07<3:40:26,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▎      | 673/2000 [1:48:20<3:59:27, 10.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▎      | 674/2000 [1:48:34<4:15:34, 11.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 675/2000 [1:48:47<4:24:15, 11.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 676/2000 [1:49:00<4:31:33, 12.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 677/2000 [1:49:05<3:44:07, 10.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 678/2000 [1:49:19<4:08:14, 11.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 679/2000 [1:49:23<3:21:05,  9.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 680/2000 [1:49:36<3:45:02, 10.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

680 işlendi | QA sayısı: 408

QA generating with Qwen:  34%|███▍      | 681/2000 [1:49:48<4:01:01, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 682/2000 [1:49:54<3:23:18,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 683/2000 [1:50:07<3:48:19, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 684/2000 [1:50:09<2:57:27,  8.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 685/2000 [1:50:12<2:24:22,  6.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 686/2000 [1:50:26<3:07:34,  8.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 687/2000 [1:50:32<2:56:18,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 688/2000 [1:50:35<2:20:34,  6.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 689/2000 [1:50:42<2:26:13,  6.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  34%|███▍      | 690/2000 [1:50:50<2:30:56,  6.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

690 işlendi | QA sayısı: 414

QA generating with Qwen:  35%|███▍      | 691/2000 [1:51:03<3:11:18,  8.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 692/2000 [1:51:11<3:05:05,  8.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 693/2000 [1:51:17<2:51:10,  7.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 694/2000 [1:51:30<3:24:55,  9.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 695/2000 [1:51:43<3:47:38, 10.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 696/2000 [1:51:56<4:04:42, 11.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 697/2000 [1:52:00<3:15:38,  9.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 698/2000 [1:52:06<2:55:18,  8.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▍      | 699/2000 [1:52:09<2:21:22,  6.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 700/2000 [1:52:20<2:51:04,  7.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

700 işlendi | QA sayısı: 421

QA generating with Qwen:  35%|███▌      | 701/2000 [1:52:30<3:06:08,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 702/2000 [1:52:43<3:33:06,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 703/2000 [1:52:46<2:46:37,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 704/2000 [1:52:54<2:48:05,  7.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 705/2000 [1:53:06<3:20:15,  9.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 706/2000 [1:53:19<3:44:51, 10.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 707/2000 [1:53:29<3:41:41, 10.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 708/2000 [1:53:42<3:56:58, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  35%|███▌      | 709/2000 [1:53:55<4:08:40, 11.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 710/2000 [1:54:08<4:18:57, 12.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

710 işlendi | QA sayısı: 426

QA generating with Qwen:  36%|███▌      | 711/2000 [1:54:15<3:44:11, 10.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 712/2000 [1:54:22<3:23:08,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 713/2000 [1:54:24<2:36:57,  7.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 714/2000 [1:54:31<2:30:43,  7.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 715/2000 [1:54:42<2:55:30,  8.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 716/2000 [1:54:47<2:39:59,  7.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 717/2000 [1:54:54<2:33:43,  7.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 718/2000 [1:55:07<3:10:59,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 719/2000 [1:55:13<2:51:35,  8.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 720/2000 [1:55:15<2:13:57,  6.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

720 işlendi | QA sayısı: 433

QA generating with Qwen:  36%|███▌      | 721/2000 [1:55:21<2:14:41,  6.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 722/2000 [1:55:27<2:07:14,  5.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 723/2000 [1:55:33<2:10:01,  6.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▌      | 724/2000 [1:55:37<1:58:00,  5.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 725/2000 [1:55:47<2:25:36,  6.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 726/2000 [1:56:00<3:02:33,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 727/2000 [1:56:13<3:29:44,  9.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 728/2000 [1:56:17<2:56:13,  8.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 729/2000 [1:56:31<3:31:30,  9.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  36%|███▋      | 730/2000 [1:56:44<3:50:23, 10.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

730 işlendi | QA sayısı: 442

QA generating with Qwen:  37%|███▋      | 731/2000 [1:56:47<2:56:59,  8.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 732/2000 [1:56:52<2:34:26,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 733/2000 [1:57:04<3:09:23,  8.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 734/2000 [1:57:08<2:33:22,  7.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 735/2000 [1:57:12<2:14:44,  6.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 736/2000 [1:57:21<2:29:09,  7.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 737/2000 [1:57:34<3:05:21,  8.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 738/2000 [1:57:45<3:22:52,  9.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 739/2000 [1:57:59<3:48:40, 10.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 740/2000 [1:58:12<4:00:18, 11.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

740 işlendi | QA sayısı: 449

QA generating with Qwen:  37%|███▋      | 741/2000 [1:58:24<4:04:27, 11.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 742/2000 [1:58:36<4:10:51, 11.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 743/2000 [1:58:49<4:15:21, 12.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 744/2000 [1:58:57<3:48:51, 10.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 745/2000 [1:59:10<4:00:30, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 746/2000 [1:59:23<4:09:07, 11.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 747/2000 [1:59:36<4:13:18, 12.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 748/2000 [1:59:48<4:16:52, 12.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  37%|███▋      | 749/2000 [1:59:50<3:12:02,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 750/2000 [1:59:53<2:30:20,  7.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

750 işlendi | QA sayısı: 453

QA generating with Qwen:  38%|███▊      | 751/2000 [1:59:59<2:25:31,  6.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 752/2000 [2:00:12<2:59:41,  8.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 753/2000 [2:00:24<3:24:30,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 754/2000 [2:00:28<2:43:42,  7.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 755/2000 [2:00:40<3:11:30,  9.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 756/2000 [2:00:52<3:30:31, 10.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 757/2000 [2:00:55<2:46:11,  8.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 758/2000 [2:01:03<2:42:46,  7.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 759/2000 [2:01:16<3:12:10,  9.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 760/2000 [2:01:28<3:32:58, 10.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

760 işlendi | QA sayısı: 459

QA generating with Qwen:  38%|███▊      | 761/2000 [2:01:42<3:52:23, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 762/2000 [2:01:54<4:00:54, 11.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 763/2000 [2:02:07<4:06:40, 11.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 764/2000 [2:02:09<3:03:46,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 765/2000 [2:02:11<2:23:04,  6.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 766/2000 [2:02:14<2:00:13,  5.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 767/2000 [2:02:20<1:56:39,  5.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 768/2000 [2:02:23<1:41:18,  4.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 769/2000 [2:02:30<1:56:27,  5.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  38%|███▊      | 770/2000 [2:02:43<2:37:25,  7.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

770 işlendi | QA sayısı: 467

QA generating with Qwen:  39%|███▊      | 771/2000 [2:02:56<3:09:04,  9.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▊      | 772/2000 [2:03:04<3:04:31,  9.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▊      | 773/2000 [2:03:06<2:22:42,  6.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▊      | 774/2000 [2:03:14<2:27:07,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 775/2000 [2:03:27<3:00:05,  8.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 776/2000 [2:03:32<2:37:33,  7.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 777/2000 [2:03:43<2:57:15,  8.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 778/2000 [2:03:49<2:43:11,  8.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 779/2000 [2:04:02<3:11:25,  9.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 780/2000 [2:04:14<3:30:44, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

780 işlendi | QA sayısı: 473

QA generating with Qwen:  39%|███▉      | 781/2000 [2:04:20<3:00:02,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 782/2000 [2:04:33<3:24:04, 10.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 783/2000 [2:04:36<2:43:18,  8.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 784/2000 [2:04:45<2:48:57,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 785/2000 [2:04:54<2:49:59,  8.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 786/2000 [2:05:01<2:47:11,  8.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 787/2000 [2:05:04<2:12:24,  6.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 788/2000 [2:05:17<2:51:08,  8.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  39%|███▉      | 789/2000 [2:05:22<2:29:31,  7.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 790/2000 [2:05:32<2:45:40,  8.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

790 işlendi | QA sayısı: 479

QA generating with Qwen:  40%|███▉      | 791/2000 [2:05:42<2:57:20,  8.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 792/2000 [2:05:45<2:18:27,  6.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 793/2000 [2:05:48<1:59:47,  5.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 794/2000 [2:05:51<1:41:51,  5.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 795/2000 [2:06:04<2:28:46,  7.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 796/2000 [2:06:17<2:59:40,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 797/2000 [2:06:30<3:26:56, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 798/2000 [2:06:40<3:22:19, 10.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|███▉      | 799/2000 [2:06:43<2:39:33,  7.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 800/2000 [2:06:56<3:09:58,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

800 işlendi | QA sayısı: 486

QA generating with Qwen:  40%|████      | 801/2000 [2:07:09<3:30:19, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 802/2000 [2:07:22<3:43:20, 11.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 803/2000 [2:07:24<2:50:16,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 804/2000 [2:07:37<3:16:46,  9.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 805/2000 [2:07:40<2:35:25,  7.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 806/2000 [2:07:46<2:25:38,  7.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 807/2000 [2:07:59<2:59:11,  9.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 808/2000 [2:08:02<2:20:47,  7.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 809/2000 [2:08:14<2:54:33,  8.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  40%|████      | 810/2000 [2:08:27<3:17:57,  9.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

810 işlendi | QA sayısı: 493

QA generating with Qwen:  41%|████      | 811/2000 [2:08:31<2:41:30,  8.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 812/2000 [2:08:44<3:08:48,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 813/2000 [2:08:57<3:27:24, 10.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 814/2000 [2:09:00<2:45:49,  8.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 815/2000 [2:09:14<3:17:13,  9.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 816/2000 [2:09:27<3:34:27, 10.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 817/2000 [2:09:30<2:49:43,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 818/2000 [2:09:43<3:13:10,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 819/2000 [2:09:55<3:29:10, 10.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 820/2000 [2:10:08<3:40:00, 11.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

820 işlendi | QA sayısı: 497

QA generating with Qwen:  41%|████      | 821/2000 [2:10:20<3:48:28, 11.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 822/2000 [2:10:27<3:16:32, 10.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 823/2000 [2:10:39<3:32:00, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████      | 824/2000 [2:10:52<3:43:42, 11.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████▏     | 825/2000 [2:10:56<3:00:25,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████▏     | 826/2000 [2:11:09<3:23:22, 10.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████▏     | 827/2000 [2:11:21<3:33:25, 10.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████▏     | 828/2000 [2:11:30<3:20:06, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  41%|████▏     | 829/2000 [2:11:40<3:15:33, 10.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 830/2000 [2:11:49<3:11:56,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

830 işlendi | QA sayısı: 504

QA generating with Qwen:  42%|████▏     | 831/2000 [2:12:02<3:30:23, 10.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 832/2000 [2:12:15<3:43:49, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 833/2000 [2:12:28<3:52:41, 11.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 834/2000 [2:12:34<3:14:17, 10.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 835/2000 [2:12:44<3:16:27, 10.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 836/2000 [2:12:47<2:37:08,  8.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 837/2000 [2:12:50<2:04:20,  6.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 838/2000 [2:13:03<2:44:16,  8.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 839/2000 [2:13:09<2:29:22,  7.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 840/2000 [2:13:12<1:59:02,  6.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

840 işlendi | QA sayısı: 510

QA generating with Qwen:  42%|████▏     | 841/2000 [2:13:15<1:40:01,  5.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 842/2000 [2:13:28<2:25:33,  7.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 843/2000 [2:13:41<2:57:43,  9.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 844/2000 [2:13:54<3:21:20, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 845/2000 [2:13:56<2:33:36,  7.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 846/2000 [2:14:03<2:27:25,  7.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 847/2000 [2:14:06<1:59:53,  6.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 848/2000 [2:14:19<2:37:55,  8.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▏     | 849/2000 [2:14:28<2:43:51,  8.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  42%|████▎     | 850/2000 [2:14:37<2:47:02,  8.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

850 işlendi | QA sayısı: 516

QA generating with Qwen:  43%|████▎     | 851/2000 [2:14:50<3:09:45,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 852/2000 [2:14:58<2:56:15,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 853/2000 [2:15:02<2:25:26,  7.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 854/2000 [2:15:06<2:08:02,  6.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 855/2000 [2:15:19<2:42:37,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 856/2000 [2:15:22<2:09:33,  6.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 857/2000 [2:15:34<2:42:56,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 858/2000 [2:15:37<2:11:04,  6.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 859/2000 [2:15:50<2:43:36,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 860/2000 [2:16:03<3:08:28,  9.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

860 işlendi | QA sayısı: 522

QA generating with Qwen:  43%|████▎     | 861/2000 [2:16:10<2:50:56,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 862/2000 [2:16:23<3:12:07, 10.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 863/2000 [2:16:25<2:27:38,  7.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 864/2000 [2:16:39<3:00:53,  9.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 865/2000 [2:16:45<2:42:45,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 866/2000 [2:16:47<2:05:24,  6.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 867/2000 [2:16:50<1:43:37,  5.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 868/2000 [2:16:57<1:52:16,  5.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  43%|████▎     | 869/2000 [2:17:08<2:21:38,  7.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▎     | 870/2000 [2:17:21<2:51:14,  9.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

870 işlendi | QA sayısı: 528

QA generating with Qwen:  44%|████▎     | 871/2000 [2:17:34<3:12:11, 10.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▎     | 872/2000 [2:17:46<3:26:06, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▎     | 873/2000 [2:17:52<2:56:21,  9.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▎     | 874/2000 [2:18:04<3:13:06, 10.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 875/2000 [2:18:16<3:22:26, 10.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 876/2000 [2:18:30<3:35:33, 11.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 877/2000 [2:18:38<3:20:33, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 878/2000 [2:18:42<2:41:40,  8.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 879/2000 [2:18:55<3:05:18,  9.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 880/2000 [2:19:00<2:35:47,  8.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

880 işlendi | QA sayısı: 535

QA generating with Qwen:  44%|████▍     | 881/2000 [2:19:02<2:02:07,  6.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 882/2000 [2:19:09<2:03:28,  6.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 883/2000 [2:19:22<2:38:26,  8.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 884/2000 [2:19:35<3:03:22,  9.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 885/2000 [2:19:48<3:19:19, 10.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 886/2000 [2:20:01<3:31:28, 11.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 887/2000 [2:20:14<3:40:57, 11.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 888/2000 [2:20:27<3:46:14, 12.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 889/2000 [2:20:35<3:23:31, 10.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  44%|████▍     | 890/2000 [2:20:41<2:57:33,  9.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

890 işlendi | QA sayısı: 540

QA generating with Qwen:  45%|████▍     | 891/2000 [2:20:54<3:15:38, 10.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 892/2000 [2:20:56<2:27:39,  8.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 893/2000 [2:20:58<1:56:49,  6.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 894/2000 [2:21:11<2:32:37,  8.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 895/2000 [2:21:25<3:00:27,  9.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 896/2000 [2:21:38<3:21:32, 10.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 897/2000 [2:21:40<2:33:35,  8.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 898/2000 [2:21:45<2:11:03,  7.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▍     | 899/2000 [2:21:58<2:44:40,  8.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 900/2000 [2:22:02<2:15:25,  7.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

900 işlendi | QA sayısı: 547

QA generating with Qwen:  45%|████▌     | 901/2000 [2:22:15<2:46:56,  9.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 902/2000 [2:22:28<3:07:54, 10.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 903/2000 [2:22:32<2:33:53,  8.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 904/2000 [2:22:44<2:55:01,  9.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 905/2000 [2:22:57<3:13:12, 10.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 906/2000 [2:23:02<2:42:08,  8.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 907/2000 [2:23:15<3:04:39, 10.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 908/2000 [2:23:28<3:22:06, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  45%|████▌     | 909/2000 [2:23:42<3:34:44, 11.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 910/2000 [2:23:55<3:42:04, 12.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

910 işlendi | QA sayısı: 553

QA generating with Qwen:  46%|████▌     | 911/2000 [2:24:09<3:49:50, 12.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 912/2000 [2:24:22<3:53:02, 12.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 913/2000 [2:24:36<3:58:10, 13.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 914/2000 [2:24:39<3:04:41, 10.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 915/2000 [2:24:42<2:25:46,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 916/2000 [2:24:55<2:53:15,  9.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 917/2000 [2:25:09<3:15:57, 10.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 918/2000 [2:25:12<2:29:28,  8.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 919/2000 [2:25:25<2:56:54,  9.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 920/2000 [2:25:31<2:35:00,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

920 işlendi | QA sayısı: 558

QA generating with Qwen:  46%|████▌     | 921/2000 [2:25:44<3:00:13, 10.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 922/2000 [2:25:57<3:18:13, 11.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 923/2000 [2:26:06<3:01:53, 10.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▌     | 924/2000 [2:26:19<3:17:44, 11.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 925/2000 [2:26:32<3:29:49, 11.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 926/2000 [2:26:36<2:49:12,  9.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 927/2000 [2:26:49<3:09:25, 10.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 928/2000 [2:27:03<3:26:05, 11.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 929/2000 [2:27:11<3:04:39, 10.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  46%|████▋     | 930/2000 [2:27:24<3:21:54, 11.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

930 işlendi | QA sayısı: 562

QA generating with Qwen:  47%|████▋     | 931/2000 [2:27:27<2:35:33,  8.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 932/2000 [2:27:40<3:00:35, 10.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 933/2000 [2:27:54<3:18:39, 11.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 934/2000 [2:28:00<2:48:48,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 935/2000 [2:28:07<2:37:19,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 936/2000 [2:28:20<2:58:55, 10.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 937/2000 [2:28:23<2:20:32,  7.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 938/2000 [2:28:28<2:07:57,  7.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 939/2000 [2:28:33<1:53:46,  6.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 940/2000 [2:28:46<2:28:04,  8.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

940 işlendi | QA sayısı: 570

QA generating with Qwen:  47%|████▋     | 941/2000 [2:28:53<2:20:16,  7.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 942/2000 [2:28:59<2:08:11,  7.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 943/2000 [2:29:03<1:52:35,  6.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 944/2000 [2:29:16<2:27:35,  8.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 945/2000 [2:29:29<2:51:48,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 946/2000 [2:29:36<2:37:09,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 947/2000 [2:29:50<3:02:16, 10.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 948/2000 [2:30:02<3:13:15, 11.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  47%|████▋     | 949/2000 [2:30:05<2:29:48,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 950/2000 [2:30:18<2:52:47,  9.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

950 işlendi | QA sayısı: 578

QA generating with Qwen:  48%|████▊     | 951/2000 [2:30:31<3:10:18, 10.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 952/2000 [2:30:36<2:38:43,  9.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 953/2000 [2:30:43<2:25:46,  8.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 954/2000 [2:30:56<2:50:58,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 955/2000 [2:31:00<2:20:01,  8.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 956/2000 [2:31:04<1:57:54,  6.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 957/2000 [2:31:17<2:30:48,  8.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 958/2000 [2:31:20<2:03:09,  7.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 959/2000 [2:31:28<2:06:52,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 960/2000 [2:31:41<2:38:08,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

960 işlendi | QA sayısı: 584

QA generating with Qwen:  48%|████▊     | 961/2000 [2:31:47<2:19:00,  8.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 962/2000 [2:32:00<2:45:09,  9.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 963/2000 [2:32:02<2:07:30,  7.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 964/2000 [2:32:05<1:42:11,  5.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 965/2000 [2:32:08<1:27:21,  5.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 966/2000 [2:32:13<1:27:32,  5.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 967/2000 [2:32:16<1:16:21,  4.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 968/2000 [2:32:18<1:05:08,  3.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 969/2000 [2:32:27<1:30:23,  5.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  48%|████▊     | 970/2000 [2:32:35<1:43:25,  6.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

970 işlendi | QA sayısı: 593

QA generating with Qwen:  49%|████▊     | 971/2000 [2:32:48<2:18:53,  8.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▊     | 972/2000 [2:32:53<2:03:13,  7.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▊     | 973/2000 [2:32:56<1:44:27,  6.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▊     | 974/2000 [2:33:03<1:49:15,  6.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 975/2000 [2:33:16<2:22:25,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 976/2000 [2:33:18<1:51:08,  6.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 977/2000 [2:33:31<2:22:26,  8.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 978/2000 [2:33:44<2:45:12,  9.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 979/2000 [2:33:49<2:23:38,  8.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 980/2000 [2:34:01<2:41:01,  9.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

980 işlendi | QA sayısı: 598

QA generating with Qwen:  49%|████▉     | 981/2000 [2:34:08<2:25:24,  8.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 982/2000 [2:34:21<2:46:54,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 983/2000 [2:34:26<2:23:12,  8.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 984/2000 [2:34:34<2:21:57,  8.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 985/2000 [2:34:37<1:56:29,  6.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 986/2000 [2:34:45<1:58:10,  6.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 987/2000 [2:34:57<2:27:28,  8.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 988/2000 [2:35:10<2:48:20,  9.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  49%|████▉     | 989/2000 [2:35:23<3:03:17, 10.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 990/2000 [2:35:37<3:16:24, 11.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

990 işlendi | QA sayısı: 604

QA generating with Qwen:  50%|████▉     | 991/2000 [2:35:39<2:27:15,  8.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 992/2000 [2:35:40<1:49:40,  6.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 993/2000 [2:35:53<2:20:36,  8.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 994/2000 [2:36:06<2:43:25,  9.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 995/2000 [2:36:08<2:06:46,  7.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 996/2000 [2:36:21<2:33:57,  9.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 997/2000 [2:36:27<2:18:33,  8.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 998/2000 [2:36:39<2:36:00,  9.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|████▉     | 999/2000 [2:36:46<2:24:53,  8.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1000/2000 [2:36:48<1:51:40,  6.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1000 işlendi | QA sayısı: 609

QA generating with Qwen:  50%|█████     | 1001/2000 [2:37:01<2:22:51,  8.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1002/2000 [2:37:14<2:44:14,  9.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1003/2000 [2:37:17<2:08:08,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1004/2000 [2:37:22<1:53:47,  6.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1005/2000 [2:37:29<1:56:32,  7.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1006/2000 [2:37:33<1:40:15,  6.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1007/2000 [2:37:46<2:15:48,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1008/2000 [2:37:52<2:05:13,  7.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1009/2000 [2:38:06<2:33:58,  9.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  50%|█████     | 1010/2000 [2:38:08<1:58:24,  7.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1010 işlendi | QA sayısı: 614

QA generating with Qwen:  51%|█████     | 1011/2000 [2:38:21<2:26:03,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1012/2000 [2:38:33<2:45:26, 10.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1013/2000 [2:38:46<2:58:17, 10.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1014/2000 [2:38:49<2:17:31,  8.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1015/2000 [2:39:01<2:38:32,  9.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1016/2000 [2:39:14<2:53:01, 10.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1017/2000 [2:39:27<3:04:53, 11.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1018/2000 [2:39:34<2:42:10,  9.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1019/2000 [2:39:41<2:28:59,  9.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1020/2000 [2:39:54<2:47:44, 10.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1020 işlendi | QA sayısı: 618

QA generating with Qwen:  51%|█████     | 1021/2000 [2:40:06<2:58:17, 10.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1022/2000 [2:40:19<3:06:17, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1023/2000 [2:40:32<3:13:21, 11.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████     | 1024/2000 [2:40:45<3:19:50, 12.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████▏    | 1025/2000 [2:40:58<3:22:18, 12.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████▏    | 1026/2000 [2:41:02<2:41:16,  9.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████▏    | 1027/2000 [2:41:15<2:55:20, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████▏    | 1028/2000 [2:41:21<2:31:32,  9.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  51%|█████▏    | 1029/2000 [2:41:34<2:49:49, 10.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1030/2000 [2:41:37<2:12:28,  8.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1030 işlendi | QA sayısı: 623

QA generating with Qwen:  52%|█████▏    | 1031/2000 [2:41:46<2:17:25,  8.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1032/2000 [2:41:49<1:47:47,  6.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1033/2000 [2:42:01<2:16:50,  8.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1034/2000 [2:42:05<1:52:56,  7.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1035/2000 [2:42:18<2:22:34,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1036/2000 [2:42:21<1:53:40,  7.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1037/2000 [2:42:32<2:12:02,  8.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1038/2000 [2:42:41<2:17:13,  8.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1039/2000 [2:42:45<1:52:06,  7.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1040/2000 [2:42:47<1:29:13,  5.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1040 işlendi | QA sayısı: 631

QA generating with Qwen:  52%|█████▏    | 1041/2000 [2:42:56<1:45:04,  6.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1042/2000 [2:43:09<2:14:58,  8.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1043/2000 [2:43:21<2:35:51,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1044/2000 [2:43:34<2:50:13, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1045/2000 [2:43:42<2:36:36,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1046/2000 [2:43:53<2:40:51, 10.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1047/2000 [2:44:06<2:53:17, 10.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1048/2000 [2:44:12<2:32:58,  9.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▏    | 1049/2000 [2:44:25<2:46:41, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  52%|█████▎    | 1050/2000 [2:44:37<2:56:16, 11.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1050 işlendi | QA sayısı: 634

QA generating with Qwen:  53%|█████▎    | 1051/2000 [2:44:46<2:44:50, 10.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1052/2000 [2:44:59<2:56:05, 11.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1053/2000 [2:45:04<2:25:39,  9.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1054/2000 [2:45:16<2:41:40, 10.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1055/2000 [2:45:29<2:53:24, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1056/2000 [2:45:35<2:27:36,  9.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1057/2000 [2:45:45<2:29:26,  9.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1058/2000 [2:45:47<1:56:25,  7.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1059/2000 [2:46:00<2:21:03,  8.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1060/2000 [2:46:10<2:25:24,  9.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1060 işlendi | QA sayısı: 639

QA generating with Qwen:  53%|█████▎    | 1061/2000 [2:46:22<2:41:42, 10.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1062/2000 [2:46:25<2:04:19,  7.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1063/2000 [2:46:32<2:00:19,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1064/2000 [2:46:35<1:37:31,  6.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1065/2000 [2:46:48<2:10:44,  8.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1066/2000 [2:46:50<1:40:08,  6.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1067/2000 [2:46:53<1:24:03,  5.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1068/2000 [2:46:58<1:21:13,  5.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  53%|█████▎    | 1069/2000 [2:47:03<1:19:07,  5.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▎    | 1070/2000 [2:47:10<1:27:59,  5.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1070 işlendi | QA sayısı: 647

QA generating with Qwen:  54%|█████▎    | 1071/2000 [2:47:15<1:26:55,  5.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▎    | 1072/2000 [2:47:17<1:07:59,  4.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▎    | 1073/2000 [2:47:30<1:48:35,  7.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▎    | 1074/2000 [2:47:34<1:36:35,  6.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1075/2000 [2:47:47<2:06:36,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1076/2000 [2:47:53<1:55:30,  7.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1077/2000 [2:48:06<2:20:15,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1078/2000 [2:48:19<2:36:54, 10.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1079/2000 [2:48:25<2:19:00,  9.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1080/2000 [2:48:38<2:36:34, 10.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1080 işlendi | QA sayısı: 653

QA generating with Qwen:  54%|█████▍    | 1081/2000 [2:48:51<2:49:10, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1082/2000 [2:48:54<2:13:59,  8.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1083/2000 [2:48:56<1:43:10,  6.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1084/2000 [2:49:02<1:38:34,  6.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1085/2000 [2:49:12<1:52:45,  7.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1086/2000 [2:49:21<1:58:43,  7.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1087/2000 [2:49:34<2:23:58,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1088/2000 [2:49:47<2:42:07, 10.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  54%|█████▍    | 1089/2000 [2:50:01<2:54:24, 11.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1090/2000 [2:50:14<3:04:27, 12.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1090 işlendi | QA sayısı: 659

QA generating with Qwen:  55%|█████▍    | 1091/2000 [2:50:16<2:17:25,  9.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1092/2000 [2:50:25<2:14:15,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1093/2000 [2:50:38<2:34:36, 10.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1094/2000 [2:50:48<2:33:30, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1095/2000 [2:51:02<2:48:52, 11.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1096/2000 [2:51:04<2:09:43,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1097/2000 [2:51:18<2:33:01, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1098/2000 [2:51:32<2:48:21, 11.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▍    | 1099/2000 [2:51:46<3:00:14, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1100/2000 [2:51:58<2:59:44, 11.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1100 işlendi | QA sayısı: 663

QA generating with Qwen:  55%|█████▌    | 1101/2000 [2:52:11<3:07:02, 12.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1102/2000 [2:52:16<2:33:17, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1103/2000 [2:52:20<2:03:34,  8.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1104/2000 [2:52:23<1:40:59,  6.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1105/2000 [2:52:26<1:25:24,  5.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1106/2000 [2:52:33<1:27:58,  5.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1107/2000 [2:52:46<2:01:39,  8.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1108/2000 [2:53:00<2:24:50,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  55%|█████▌    | 1109/2000 [2:53:02<1:53:40,  7.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1110/2000 [2:53:10<1:51:31,  7.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1110 işlendi | QA sayısı: 671

QA generating with Qwen:  56%|█████▌    | 1111/2000 [2:53:23<2:17:58,  9.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1112/2000 [2:53:36<2:35:25, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1113/2000 [2:53:40<2:04:54,  8.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1114/2000 [2:53:43<1:38:32,  6.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1115/2000 [2:53:49<1:38:25,  6.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1116/2000 [2:54:02<2:07:19,  8.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1117/2000 [2:54:10<2:00:30,  8.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1118/2000 [2:54:23<2:21:52,  9.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1119/2000 [2:54:36<2:36:40, 10.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1120/2000 [2:54:49<2:47:19, 11.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1120 işlendi | QA sayısı: 675

QA generating with Qwen:  56%|█████▌    | 1121/2000 [2:55:02<2:55:34, 11.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1122/2000 [2:55:16<3:03:56, 12.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1123/2000 [2:55:29<3:05:48, 12.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▌    | 1124/2000 [2:55:43<3:08:52, 12.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1125/2000 [2:55:56<3:09:14, 12.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1126/2000 [2:56:08<3:08:08, 12.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1127/2000 [2:56:13<2:31:36, 10.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1128/2000 [2:56:26<2:41:07, 11.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1129/2000 [2:56:35<2:33:32, 10.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  56%|█████▋    | 1130/2000 [2:56:42<2:16:11,  9.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1130 işlendi | QA sayısı: 680

QA generating with Qwen:  57%|█████▋    | 1131/2000 [2:56:55<2:31:43, 10.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1132/2000 [2:57:08<2:42:57, 11.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1133/2000 [2:57:13<2:15:10,  9.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1134/2000 [2:57:15<1:46:25,  7.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1135/2000 [2:57:29<2:11:14,  9.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1136/2000 [2:57:31<1:43:18,  7.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1137/2000 [2:57:45<2:09:30,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1138/2000 [2:57:58<2:27:40, 10.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1139/2000 [2:58:00<1:52:42,  7.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1140/2000 [2:58:02<1:27:10,  6.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1140 işlendi | QA sayısı: 688

QA generating with Qwen:  57%|█████▋    | 1141/2000 [2:58:15<1:57:34,  8.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1142/2000 [2:58:18<1:33:30,  6.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1143/2000 [2:58:31<2:00:25,  8.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1144/2000 [2:58:44<2:20:09,  9.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1145/2000 [2:58:47<1:51:32,  7.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1146/2000 [2:59:00<2:12:29,  9.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1147/2000 [2:59:10<2:18:49,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1148/2000 [2:59:23<2:32:12, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▋    | 1149/2000 [2:59:36<2:42:04, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  57%|█████▊    | 1150/2000 [2:59:42<2:16:31,  9.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1150 işlendi | QA sayısı: 694

QA generating with Qwen:  58%|█████▊    | 1151/2000 [2:59:55<2:29:06, 10.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1152/2000 [3:00:07<2:38:40, 11.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1153/2000 [3:00:18<2:36:58, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1154/2000 [3:00:26<2:22:49, 10.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1155/2000 [3:00:32<2:03:57,  8.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1156/2000 [3:00:45<2:21:17, 10.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1157/2000 [3:00:58<2:34:03, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1158/2000 [3:01:01<1:59:59,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1159/2000 [3:01:11<2:05:19,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1160/2000 [3:01:23<2:21:26, 10.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1160 işlendi | QA sayısı: 698

QA generating with Qwen:  58%|█████▊    | 1161/2000 [3:01:26<1:50:35,  7.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1162/2000 [3:01:39<2:12:29,  9.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1163/2000 [3:01:53<2:28:12, 10.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1164/2000 [3:01:56<1:55:36,  8.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1165/2000 [3:01:59<1:36:04,  6.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1166/2000 [3:02:06<1:33:34,  6.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1167/2000 [3:02:10<1:22:49,  5.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1168/2000 [3:02:23<1:51:37,  8.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1169/2000 [3:02:33<2:01:40,  8.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  58%|█████▊    | 1170/2000 [3:02:47<2:21:36, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1170 işlendi | QA sayısı: 705

QA generating with Qwen:  59%|█████▊    | 1171/2000 [3:02:55<2:15:00,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▊    | 1172/2000 [3:02:59<1:47:02,  7.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▊    | 1173/2000 [3:03:11<2:07:43,  9.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▊    | 1174/2000 [3:03:24<2:23:10, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1175/2000 [3:03:33<2:16:57,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1176/2000 [3:03:39<1:57:28,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1177/2000 [3:03:44<1:43:00,  7.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1178/2000 [3:03:57<2:06:18,  9.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1179/2000 [3:04:10<2:20:56, 10.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1180/2000 [3:04:14<1:55:12,  8.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1180 işlendi | QA sayısı: 713

QA generating with Qwen:  59%|█████▉    | 1181/2000 [3:04:20<1:46:50,  7.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1182/2000 [3:04:33<2:06:59,  9.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1183/2000 [3:04:36<1:42:51,  7.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1184/2000 [3:04:50<2:05:42,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1185/2000 [3:04:56<1:52:46,  8.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1186/2000 [3:05:08<2:10:52,  9.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1187/2000 [3:05:21<2:23:57, 10.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1188/2000 [3:05:25<1:56:02,  8.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  59%|█████▉    | 1189/2000 [3:05:38<2:14:43,  9.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1190/2000 [3:05:52<2:28:06, 10.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1190 işlendi | QA sayısı: 721

QA generating with Qwen:  60%|█████▉    | 1191/2000 [3:06:05<2:37:53, 11.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1192/2000 [3:06:16<2:33:34, 11.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1193/2000 [3:06:29<2:40:04, 11.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1194/2000 [3:06:35<2:17:00, 10.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1195/2000 [3:06:49<2:30:49, 11.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1196/2000 [3:07:02<2:39:06, 11.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1197/2000 [3:07:12<2:30:23, 11.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1198/2000 [3:07:23<2:30:28, 11.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|█████▉    | 1199/2000 [3:07:36<2:37:45, 11.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1200/2000 [3:07:43<2:15:27, 10.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1200 işlendi | QA sayısı: 729

QA generating with Qwen:  60%|██████    | 1201/2000 [3:07:45<1:43:01,  7.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1202/2000 [3:07:58<2:04:06,  9.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1203/2000 [3:08:11<2:18:47, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1204/2000 [3:08:24<2:29:35, 11.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1205/2000 [3:08:37<2:36:46, 11.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1206/2000 [3:08:50<2:41:20, 12.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1207/2000 [3:08:59<2:29:50, 11.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1208/2000 [3:09:12<2:36:10, 11.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1209/2000 [3:09:25<2:39:57, 12.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  60%|██████    | 1210/2000 [3:09:38<2:41:01, 12.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1210 işlendi | QA sayısı: 734

QA generating with Qwen:  61%|██████    | 1211/2000 [3:09:48<2:34:03, 11.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1212/2000 [3:09:59<2:29:32, 11.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1213/2000 [3:10:01<1:54:40,  8.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1214/2000 [3:10:14<2:10:39,  9.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1215/2000 [3:10:27<2:22:34, 10.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1216/2000 [3:10:35<2:10:12,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1217/2000 [3:10:39<1:45:13,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1218/2000 [3:10:52<2:04:55,  9.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1219/2000 [3:11:05<2:19:03, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1220/2000 [3:11:18<2:27:35, 11.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1220 işlendi | QA sayısı: 741

QA generating with Qwen:  61%|██████    | 1221/2000 [3:11:22<1:58:20,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1222/2000 [3:11:35<2:14:05, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1223/2000 [3:11:38<1:44:51,  8.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████    | 1224/2000 [3:11:41<1:26:14,  6.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████▏   | 1225/2000 [3:11:44<1:11:44,  5.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████▏   | 1226/2000 [3:11:48<1:03:51,  4.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████▏   | 1227/2000 [3:11:51<56:57,  4.42s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████▏   | 1228/2000 [3:11:54<52:59,  4.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  61%|██████▏   | 1229/2000 [3:12:07<1:26:38,  6.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1230/2000 [3:12:13<1:21:17,  6.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1230 işlendi | QA sayısı: 748

QA generating with Qwen:  62%|██████▏   | 1231/2000 [3:12:26<1:46:01,  8.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1232/2000 [3:12:38<2:02:26,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1233/2000 [3:12:45<1:50:25,  8.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1234/2000 [3:12:58<2:07:19,  9.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1235/2000 [3:13:11<2:18:17, 10.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1236/2000 [3:13:23<2:25:31, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1237/2000 [3:13:36<2:30:41, 11.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1238/2000 [3:13:41<2:04:36,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1239/2000 [3:13:54<2:17:30, 10.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1240/2000 [3:14:00<1:58:49,  9.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1240 işlendi | QA sayısı: 754

QA generating with Qwen:  62%|██████▏   | 1241/2000 [3:14:13<2:11:02, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1242/2000 [3:14:22<2:05:55,  9.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1243/2000 [3:14:29<1:53:36,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1244/2000 [3:14:32<1:30:07,  7.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1245/2000 [3:14:45<1:51:22,  8.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1246/2000 [3:14:47<1:28:31,  7.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1247/2000 [3:14:51<1:14:57,  5.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1248/2000 [3:14:56<1:11:56,  5.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▏   | 1249/2000 [3:15:08<1:36:46,  7.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  62%|██████▎   | 1250/2000 [3:15:10<1:13:54,  5.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1250 işlendi | QA sayısı: 762

QA generating with Qwen:  63%|██████▎   | 1251/2000 [3:15:15<1:11:44,  5.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1252/2000 [3:15:26<1:30:28,  7.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1253/2000 [3:15:39<1:50:59,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1254/2000 [3:15:47<1:48:17,  8.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1255/2000 [3:16:00<2:02:52,  9.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1256/2000 [3:16:07<1:50:47,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1257/2000 [3:16:19<2:04:32, 10.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1258/2000 [3:16:30<2:06:24, 10.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1259/2000 [3:16:42<2:14:17, 10.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1260/2000 [3:16:45<1:44:40,  8.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1260 işlendi | QA sayısı: 767

QA generating with Qwen:  63%|██████▎   | 1261/2000 [3:16:58<2:00:51,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1262/2000 [3:17:02<1:38:06,  7.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1263/2000 [3:17:15<1:56:07,  9.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1264/2000 [3:17:28<2:08:49, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1265/2000 [3:17:41<2:17:24, 11.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1266/2000 [3:17:53<2:23:23, 11.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1267/2000 [3:18:06<2:27:36, 12.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1268/2000 [3:18:19<2:30:24, 12.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  63%|██████▎   | 1269/2000 [3:18:32<2:32:17, 12.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▎   | 1270/2000 [3:18:45<2:33:59, 12.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1270 işlendi | QA sayısı: 770

QA generating with Qwen:  64%|██████▎   | 1271/2000 [3:18:49<2:00:03,  9.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▎   | 1272/2000 [3:19:02<2:11:06, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▎   | 1273/2000 [3:19:14<2:18:27, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▎   | 1274/2000 [3:19:28<2:24:38, 11.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1275/2000 [3:19:40<2:27:50, 12.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1276/2000 [3:19:54<2:31:13, 12.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1277/2000 [3:20:00<2:09:43, 10.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1278/2000 [3:20:06<1:51:40,  9.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1279/2000 [3:20:19<2:03:12, 10.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1280/2000 [3:20:24<1:44:58,  8.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1280 işlendi | QA sayısı: 775

QA generating with Qwen:  64%|██████▍   | 1281/2000 [3:20:26<1:19:21,  6.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1282/2000 [3:20:39<1:42:41,  8.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1283/2000 [3:20:52<1:58:02,  9.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1284/2000 [3:21:05<2:08:50, 10.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1285/2000 [3:21:17<2:16:08, 11.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1286/2000 [3:21:30<2:21:10, 11.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1287/2000 [3:21:36<1:57:04,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1288/2000 [3:21:48<2:07:47, 10.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1289/2000 [3:22:01<2:15:07, 11.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  64%|██████▍   | 1290/2000 [3:22:09<2:01:46, 10.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1290 işlendi | QA sayısı: 780

QA generating with Qwen:  65%|██████▍   | 1291/2000 [3:22:13<1:40:04,  8.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1292/2000 [3:22:16<1:18:05,  6.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1293/2000 [3:22:19<1:06:04,  5.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1294/2000 [3:22:22<59:19,  5.04s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1295/2000 [3:22:36<1:27:42,  7.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1296/2000 [3:22:48<1:45:33,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1297/2000 [3:23:01<1:59:10, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1298/2000 [3:23:06<1:39:43,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▍   | 1299/2000 [3:23:10<1:24:04,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1300/2000 [3:23:23<1:43:11,  8.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1300 işlendi | QA sayısı: 788

QA generating with Qwen:  65%|██████▌   | 1301/2000 [3:23:27<1:27:01,  7.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1302/2000 [3:23:36<1:33:03,  8.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1303/2000 [3:23:42<1:25:26,  7.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1304/2000 [3:23:55<1:45:05,  9.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1305/2000 [3:24:08<1:59:53, 10.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1306/2000 [3:24:22<2:09:58, 11.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1307/2000 [3:24:35<2:16:01, 11.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1308/2000 [3:24:42<1:59:02, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  65%|██████▌   | 1309/2000 [3:24:48<1:46:48,  9.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1310/2000 [3:25:02<2:00:19, 10.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1310 işlendi | QA sayısı: 795

QA generating with Qwen:  66%|██████▌   | 1311/2000 [3:25:10<1:54:04,  9.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1312/2000 [3:25:23<2:04:35, 10.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1313/2000 [3:25:37<2:12:22, 11.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1314/2000 [3:25:50<2:18:37, 12.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1315/2000 [3:26:03<2:22:13, 12.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1316/2000 [3:26:05<1:46:32,  9.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1317/2000 [3:26:09<1:25:58,  7.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1318/2000 [3:26:17<1:26:53,  7.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1319/2000 [3:26:25<1:28:16,  7.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1320/2000 [3:26:38<1:45:56,  9.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1320 işlendi | QA sayısı: 801

QA generating with Qwen:  66%|██████▌   | 1321/2000 [3:26:51<1:58:19, 10.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1322/2000 [3:26:58<1:48:10,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1323/2000 [3:27:11<2:00:12, 10.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▌   | 1324/2000 [3:27:18<1:46:20,  9.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1325/2000 [3:27:32<2:00:09, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1326/2000 [3:27:45<2:09:59, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1327/2000 [3:27:47<1:38:13,  8.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1328/2000 [3:28:02<1:58:29, 10.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1329/2000 [3:28:15<2:07:17, 11.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  66%|██████▋   | 1330/2000 [3:28:29<2:13:52, 11.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1330 işlendi | QA sayısı: 805

QA generating with Qwen:  67%|██████▋   | 1331/2000 [3:28:42<2:19:01, 12.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1332/2000 [3:28:48<1:56:12, 10.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1333/2000 [3:29:02<2:07:07, 11.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1334/2000 [3:29:16<2:15:03, 12.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1335/2000 [3:29:30<2:20:00, 12.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1336/2000 [3:29:43<2:22:51, 12.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1337/2000 [3:29:57<2:25:48, 13.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1338/2000 [3:30:10<2:26:32, 13.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1339/2000 [3:30:24<2:26:52, 13.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1340/2000 [3:30:29<1:58:05, 10.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1340 işlendi | QA sayısı: 811

QA generating with Qwen:  67%|██████▋   | 1341/2000 [3:30:41<2:03:27, 11.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1342/2000 [3:30:47<1:44:56,  9.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1343/2000 [3:31:00<1:58:30, 10.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1344/2000 [3:31:14<2:08:01, 11.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1345/2000 [3:31:28<2:15:23, 12.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1346/2000 [3:31:42<2:18:59, 12.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1347/2000 [3:31:55<2:21:33, 13.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1348/2000 [3:32:00<1:54:45, 10.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  67%|██████▋   | 1349/2000 [3:32:02<1:26:31,  7.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1350/2000 [3:32:16<1:44:20,  9.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1350 işlendi | QA sayısı: 815

QA generating with Qwen:  68%|██████▊   | 1351/2000 [3:32:22<1:31:52,  8.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1352/2000 [3:32:35<1:47:59, 10.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1353/2000 [3:32:48<1:58:57, 11.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1354/2000 [3:33:02<2:06:55, 11.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1355/2000 [3:33:15<2:11:57, 12.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1356/2000 [3:33:29<2:17:29, 12.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1357/2000 [3:33:43<2:19:33, 13.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1358/2000 [3:33:56<2:20:23, 13.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1359/2000 [3:33:59<1:47:55, 10.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1360/2000 [3:34:13<1:57:24, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1360 işlendi | QA sayısı: 820

QA generating with Qwen:  68%|██████▊   | 1361/2000 [3:34:26<2:04:11, 11.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1362/2000 [3:34:39<2:09:40, 12.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1363/2000 [3:34:51<2:07:59, 12.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1364/2000 [3:35:04<2:12:01, 12.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1365/2000 [3:35:17<2:14:12, 12.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1366/2000 [3:35:31<2:15:58, 12.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1367/2000 [3:35:37<1:55:49, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1368/2000 [3:35:51<2:03:36, 11.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1369/2000 [3:36:04<2:09:20, 12.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  68%|██████▊   | 1370/2000 [3:36:10<1:48:21, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1370 işlendi | QA sayısı: 826

QA generating with Qwen:  69%|██████▊   | 1371/2000 [3:36:14<1:27:41,  8.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▊   | 1372/2000 [3:36:27<1:43:02,  9.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▊   | 1373/2000 [3:36:41<1:53:43, 10.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▊   | 1374/2000 [3:36:50<1:48:05, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1375/2000 [3:36:55<1:32:59,  8.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1376/2000 [3:36:58<1:12:08,  6.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1377/2000 [3:37:11<1:32:57,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1378/2000 [3:37:25<1:46:12, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1379/2000 [3:37:38<1:55:24, 11.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1380/2000 [3:37:41<1:29:48,  8.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1380 işlendi | QA sayısı: 831

QA generating with Qwen:  69%|██████▉   | 1381/2000 [3:37:54<1:42:31,  9.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1382/2000 [3:38:01<1:34:07,  9.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1383/2000 [3:38:14<1:46:26, 10.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1384/2000 [3:38:27<1:55:30, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1385/2000 [3:38:36<1:47:54, 10.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1386/2000 [3:38:49<1:56:04, 11.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1387/2000 [3:39:02<1:58:23, 11.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1388/2000 [3:39:15<2:03:59, 12.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  69%|██████▉   | 1389/2000 [3:39:28<2:07:29, 12.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1390/2000 [3:39:42<2:09:55, 12.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1390 işlendi | QA sayısı: 834

QA generating with Qwen:  70%|██████▉   | 1391/2000 [3:39:55<2:11:34, 12.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1392/2000 [3:40:09<2:12:47, 13.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1393/2000 [3:40:22<2:12:44, 13.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1394/2000 [3:40:25<1:41:02, 10.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1395/2000 [3:40:37<1:49:41, 10.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1396/2000 [3:40:50<1:55:45, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1397/2000 [3:41:04<2:01:14, 12.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1398/2000 [3:41:17<2:04:37, 12.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|██████▉   | 1399/2000 [3:41:27<1:56:11, 11.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1400/2000 [3:41:35<1:47:05, 10.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1400 işlendi | QA sayısı: 839

QA generating with Qwen:  70%|███████   | 1401/2000 [3:41:49<1:54:38, 11.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1402/2000 [3:41:52<1:31:05,  9.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1403/2000 [3:42:06<1:43:23, 10.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1404/2000 [3:42:19<1:51:43, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1405/2000 [3:42:32<1:57:53, 11.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1406/2000 [3:42:45<2:00:47, 12.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1407/2000 [3:42:53<1:47:28, 10.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1408/2000 [3:43:07<1:55:16, 11.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1409/2000 [3:43:14<1:43:26, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  70%|███████   | 1410/2000 [3:43:19<1:27:10,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1410 işlendi | QA sayısı: 844

QA generating with Qwen:  71%|███████   | 1411/2000 [3:43:33<1:40:54, 10.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1412/2000 [3:43:34<1:14:39,  7.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1413/2000 [3:43:47<1:28:04,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1414/2000 [3:44:00<1:40:05, 10.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1415/2000 [3:44:07<1:31:08,  9.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1416/2000 [3:44:20<1:41:45, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1417/2000 [3:44:33<1:49:35, 11.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1418/2000 [3:44:46<1:53:50, 11.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1419/2000 [3:44:59<1:56:42, 12.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1420/2000 [3:45:12<1:59:26, 12.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1420 işlendi | QA sayısı: 848

QA generating with Qwen:  71%|███████   | 1421/2000 [3:45:25<2:00:03, 12.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1422/2000 [3:45:38<2:01:42, 12.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1423/2000 [3:45:51<2:02:29, 12.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████   | 1424/2000 [3:46:04<2:03:25, 12.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████▏  | 1425/2000 [3:46:06<1:33:23,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████▏  | 1426/2000 [3:46:17<1:35:33,  9.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████▏  | 1427/2000 [3:46:30<1:44:01, 10.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████▏  | 1428/2000 [3:46:43<1:50:54, 11.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  71%|███████▏  | 1429/2000 [3:46:51<1:40:55, 10.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1430/2000 [3:47:05<1:48:49, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1430 işlendi | QA sayısı: 853

QA generating with Qwen:  72%|███████▏  | 1431/2000 [3:47:14<1:41:16, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1432/2000 [3:47:27<1:47:17, 11.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1433/2000 [3:47:29<1:22:28,  8.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1434/2000 [3:47:42<1:34:36, 10.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1435/2000 [3:47:55<1:43:10, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1436/2000 [3:48:01<1:29:08,  9.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1437/2000 [3:48:12<1:33:09,  9.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1438/2000 [3:48:25<1:40:51, 10.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1439/2000 [3:48:30<1:24:37,  9.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1440/2000 [3:48:35<1:13:14,  7.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1440 işlendi | QA sayısı: 857

QA generating with Qwen:  72%|███████▏  | 1441/2000 [3:48:42<1:09:39,  7.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1442/2000 [3:48:49<1:08:15,  7.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1443/2000 [3:49:02<1:23:48,  9.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1444/2000 [3:49:15<1:34:28, 10.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1445/2000 [3:49:28<1:41:50, 11.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1446/2000 [3:49:41<1:46:55, 11.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1447/2000 [3:49:54<1:50:41, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1448/2000 [3:49:56<1:24:01,  9.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▏  | 1449/2000 [3:50:03<1:17:00,  8.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  72%|███████▎  | 1450/2000 [3:50:16<1:30:18,  9.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1450 işlendi | QA sayısı: 862

QA generating with Qwen:  73%|███████▎  | 1451/2000 [3:50:29<1:38:41, 10.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1452/2000 [3:50:42<1:45:09, 11.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1453/2000 [3:50:46<1:24:22,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1454/2000 [3:50:51<1:11:45,  7.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1455/2000 [3:51:04<1:25:55,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1456/2000 [3:51:17<1:35:26, 10.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1457/2000 [3:51:30<1:42:19, 11.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1458/2000 [3:51:43<1:46:55, 11.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1459/2000 [3:51:52<1:40:05, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1460/2000 [3:51:57<1:21:54,  9.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1460 işlendi | QA sayısı: 866

QA generating with Qwen:  73%|███████▎  | 1461/2000 [3:52:10<1:32:51, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1462/2000 [3:52:23<1:39:52, 11.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1463/2000 [3:52:36<1:44:58, 11.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1464/2000 [3:52:49<1:47:39, 12.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1465/2000 [3:53:02<1:49:45, 12.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1466/2000 [3:53:07<1:29:42, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1467/2000 [3:53:12<1:16:31,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1468/2000 [3:53:19<1:11:21,  8.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  73%|███████▎  | 1469/2000 [3:53:32<1:24:05,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▎  | 1470/2000 [3:53:34<1:03:46,  7.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1470 işlendi | QA sayısı: 871

QA generating with Qwen:  74%|███████▎  | 1471/2000 [3:53:39<58:53,  6.68s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▎  | 1472/2000 [3:53:52<1:14:36,  8.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▎  | 1473/2000 [3:54:05<1:26:10,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▎  | 1474/2000 [3:54:11<1:16:21,  8.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1475/2000 [3:54:16<1:07:30,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1476/2000 [3:54:29<1:20:42,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1477/2000 [3:54:35<1:12:38,  8.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1478/2000 [3:54:38<58:32,  6.73s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1479/2000 [3:54:51<1:14:19,  8.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1480/2000 [3:55:04<1:25:34,  9.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1480 işlendi | QA sayısı: 877

QA generating with Qwen:  74%|███████▍  | 1481/2000 [3:55:07<1:07:48,  7.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1482/2000 [3:55:19<1:19:51,  9.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1483/2000 [3:55:32<1:28:48, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1484/2000 [3:55:45<1:34:56, 11.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1485/2000 [3:55:58<1:39:40, 11.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1486/2000 [3:56:11<1:42:50, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1487/2000 [3:56:21<1:38:49, 11.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1488/2000 [3:56:24<1:15:12,  8.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1489/2000 [3:56:37<1:25:06,  9.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  74%|███████▍  | 1490/2000 [3:56:49<1:32:00, 10.82s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1490 işlendi | QA sayısı: 885

QA generating with Qwen:  75%|███████▍  | 1491/2000 [3:56:52<1:10:43,  8.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1492/2000 [3:56:55<57:09,  6.75s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1493/2000 [3:56:57<45:08,  5.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1494/2000 [3:57:10<1:04:54,  7.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1495/2000 [3:57:13<51:41,  6.14s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1496/2000 [3:57:26<1:08:46,  8.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1497/2000 [3:57:29<57:32,  6.86s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1498/2000 [3:57:32<47:24,  5.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▍  | 1499/2000 [3:57:36<41:37,  4.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1500/2000 [3:57:48<1:01:05,  7.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1500 işlendi | QA sayısı: 893

QA generating with Qwen:  75%|███████▌  | 1501/2000 [3:58:01<1:14:46,  8.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1502/2000 [3:58:04<59:05,  7.12s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1503/2000 [3:58:17<1:13:21,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1504/2000 [3:58:30<1:23:29, 10.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1505/2000 [3:58:43<1:30:18, 10.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1506/2000 [3:58:56<1:34:55, 11.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1507/2000 [3:58:59<1:15:17,  9.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1508/2000 [3:59:03<1:00:42,  7.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  75%|███████▌  | 1509/2000 [3:59:08<56:10,  6.87s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1510/2000 [3:59:20<1:06:47,  8.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1510 işlendi | QA sayısı: 898

QA generating with Qwen:  76%|███████▌  | 1511/2000 [3:59:26<1:03:28,  7.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1512/2000 [3:59:39<1:15:45,  9.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1513/2000 [3:59:53<1:25:40, 10.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1514/2000 [4:00:01<1:18:43,  9.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1515/2000 [4:00:14<1:27:12, 10.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1516/2000 [4:00:27<1:32:28, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1517/2000 [4:00:39<1:33:35, 11.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1518/2000 [4:00:52<1:36:52, 12.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1519/2000 [4:01:05<1:39:05, 12.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1520/2000 [4:01:08<1:16:04,  9.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1520 işlendi | QA sayısı: 905

QA generating with Qwen:  76%|███████▌  | 1521/2000 [4:01:12<1:03:13,  7.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1522/2000 [4:01:25<1:15:39,  9.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1523/2000 [4:01:28<58:12,  7.32s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▌  | 1524/2000 [4:01:41<1:12:01,  9.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1525/2000 [4:01:54<1:21:51, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1526/2000 [4:02:05<1:22:57, 10.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1527/2000 [4:02:18<1:28:52, 11.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1528/2000 [4:02:31<1:33:14, 11.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1529/2000 [4:02:44<1:35:44, 12.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  76%|███████▋  | 1530/2000 [4:02:57<1:36:59, 12.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1530 işlendi | QA sayısı: 909

QA generating with Qwen:  77%|███████▋  | 1531/2000 [4:03:07<1:30:24, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1532/2000 [4:03:10<1:11:46,  9.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1533/2000 [4:03:23<1:19:46, 10.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1534/2000 [4:03:36<1:25:53, 11.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1535/2000 [4:03:49<1:30:31, 11.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1536/2000 [4:04:02<1:33:17, 12.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1537/2000 [4:04:15<1:35:54, 12.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1538/2000 [4:04:29<1:38:00, 12.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1539/2000 [4:04:35<1:22:47, 10.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1540/2000 [4:04:45<1:20:04, 10.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1540 işlendi | QA sayısı: 914

QA generating with Qwen:  77%|███████▋  | 1541/2000 [4:04:47<1:01:35,  8.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1542/2000 [4:04:55<1:01:22,  8.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1543/2000 [4:05:00<53:19,  7.00s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1544/2000 [4:05:04<46:19,  6.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1545/2000 [4:05:17<1:02:21,  8.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1546/2000 [4:05:26<1:04:49,  8.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1547/2000 [4:05:39<1:15:04,  9.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1548/2000 [4:05:52<1:21:26, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  77%|███████▋  | 1549/2000 [4:06:05<1:26:17, 11.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1550/2000 [4:06:13<1:18:20, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1550 işlendi | QA sayısı: 920

QA generating with Qwen:  78%|███████▊  | 1551/2000 [4:06:26<1:23:28, 11.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1552/2000 [4:06:29<1:04:35,  8.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1553/2000 [4:06:42<1:14:14,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1554/2000 [4:06:48<1:04:32,  8.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1555/2000 [4:06:51<53:19,  7.19s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1556/2000 [4:06:56<47:47,  6.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1557/2000 [4:07:04<50:11,  6.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1558/2000 [4:07:10<48:04,  6.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1559/2000 [4:07:13<41:19,  5.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1560/2000 [4:07:16<35:35,  4.85s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1560 işlendi | QA sayısı: 928

QA generating with Qwen:  78%|███████▊  | 1561/2000 [4:07:29<53:25,  7.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1562/2000 [4:07:36<51:37,  7.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1563/2000 [4:07:49<1:04:42,  8.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1564/2000 [4:07:53<54:28,  7.50s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1565/2000 [4:07:57<46:29,  6.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1566/2000 [4:08:10<1:00:38,  8.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1567/2000 [4:08:19<1:02:03,  8.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1568/2000 [4:08:26<57:24,  7.97s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1569/2000 [4:08:38<1:07:21,  9.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  78%|███████▊  | 1570/2000 [4:08:51<1:14:52, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1570 işlendi | QA sayısı: 934

QA generating with Qwen:  79%|███████▊  | 1571/2000 [4:09:04<1:20:14, 11.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▊  | 1572/2000 [4:09:17<1:24:04, 11.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▊  | 1573/2000 [4:09:20<1:03:48,  8.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▊  | 1574/2000 [4:09:25<56:47,  8.00s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1575/2000 [4:09:38<1:07:12,  9.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1576/2000 [4:09:51<1:14:16, 10.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1577/2000 [4:10:04<1:19:17, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1578/2000 [4:10:15<1:18:09, 11.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1579/2000 [4:10:28<1:22:39, 11.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1580/2000 [4:10:41<1:25:04, 12.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1580 işlendi | QA sayısı: 942

QA generating with Qwen:  79%|███████▉  | 1581/2000 [4:10:52<1:20:55, 11.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1582/2000 [4:11:04<1:23:14, 11.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1583/2000 [4:11:08<1:05:29,  9.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1584/2000 [4:11:21<1:13:33, 10.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1585/2000 [4:11:31<1:11:06, 10.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1586/2000 [4:11:34<56:34,  8.20s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1587/2000 [4:11:40<51:26,  7.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1588/2000 [4:11:48<51:40,  7.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  79%|███████▉  | 1589/2000 [4:12:01<1:03:00,  9.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1590/2000 [4:12:14<1:10:53, 10.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1590 işlendi | QA sayısı: 949

QA generating with Qwen:  80%|███████▉  | 1591/2000 [4:12:27<1:15:34, 11.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1592/2000 [4:12:30<1:00:20,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1593/2000 [4:12:43<1:08:52, 10.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1594/2000 [4:12:46<53:28,  7.90s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1595/2000 [4:12:59<1:03:58,  9.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1596/2000 [4:13:01<48:25,  7.19s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1597/2000 [4:13:15<1:01:11,  9.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1598/2000 [4:13:16<46:02,  6.87s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|███████▉  | 1599/2000 [4:13:24<47:03,  7.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1600/2000 [4:13:26<36:59,  5.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1600 işlendi | QA sayısı: 955

QA generating with Qwen:  80%|████████  | 1601/2000 [4:13:39<52:32,  7.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1602/2000 [4:13:42<41:46,  6.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1603/2000 [4:13:55<55:43,  8.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1604/2000 [4:14:08<1:04:41,  9.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1605/2000 [4:14:11<50:43,  7.71s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1606/2000 [4:14:24<1:01:06,  9.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1607/2000 [4:14:37<1:07:49, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1608/2000 [4:14:41<56:03,  8.58s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1609/2000 [4:14:50<56:04,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  80%|████████  | 1610/2000 [4:14:57<52:41,  8.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1610 işlendi | QA sayısı: 959

QA generating with Qwen:  81%|████████  | 1611/2000 [4:15:10<1:02:48,  9.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1612/2000 [4:15:13<49:44,  7.69s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1613/2000 [4:15:21<48:44,  7.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1614/2000 [4:15:23<38:41,  6.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1615/2000 [4:15:26<32:57,  5.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1616/2000 [4:15:29<28:24,  4.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1617/2000 [4:15:38<37:07,  5.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1618/2000 [4:15:43<36:21,  5.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1619/2000 [4:15:56<50:17,  7.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1620/2000 [4:16:10<1:00:01,  9.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1620 işlendi | QA sayısı: 967

QA generating with Qwen:  81%|████████  | 1621/2000 [4:16:16<53:19,  8.44s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1622/2000 [4:16:23<51:31,  8.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1623/2000 [4:16:36<1:00:02,  9.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████  | 1624/2000 [4:16:49<1:06:36, 10.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████▏ | 1625/2000 [4:16:52<51:15,  8.20s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████▏ | 1626/2000 [4:17:05<1:00:18,  9.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████▏ | 1627/2000 [4:17:08<47:38,  7.66s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████▏ | 1628/2000 [4:17:21<58:38,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  81%|████████▏ | 1629/2000 [4:17:34<1:05:20, 10.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1630/2000 [4:17:38<51:38,  8.37s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1630 işlendi | QA sayısı: 973

QA generating with Qwen:  82%|████████▏ | 1631/2000 [4:17:43<46:10,  7.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1632/2000 [4:17:51<45:59,  7.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1633/2000 [4:18:04<56:24,  9.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1634/2000 [4:18:17<1:03:14, 10.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1635/2000 [4:18:19<48:19,  7.94s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1636/2000 [4:18:32<57:33,  9.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1637/2000 [4:18:41<56:11,  9.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1638/2000 [4:18:43<43:24,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1639/2000 [4:18:57<53:58,  8.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1640/2000 [4:18:59<41:44,  6.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1640 işlendi | QA sayısı: 979

QA generating with Qwen:  82%|████████▏ | 1641/2000 [4:19:12<53:05,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1642/2000 [4:19:19<48:32,  8.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1643/2000 [4:19:32<57:36,  9.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1644/2000 [4:19:45<1:03:37, 10.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1645/2000 [4:19:58<1:08:00, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1646/2000 [4:20:10<1:08:19, 11.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1647/2000 [4:20:23<1:10:40, 12.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1648/2000 [4:20:37<1:12:50, 12.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▏ | 1649/2000 [4:20:50<1:13:53, 12.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  82%|████████▎ | 1650/2000 [4:21:03<1:15:08, 12.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1650 işlendi | QA sayısı: 982

QA generating with Qwen:  83%|████████▎ | 1651/2000 [4:21:07<58:55, 10.13s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1652/2000 [4:21:09<44:08,  7.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1653/2000 [4:21:22<53:48,  9.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1654/2000 [4:21:24<42:08,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1655/2000 [4:21:38<52:32,  9.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1656/2000 [4:21:41<42:31,  7.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1657/2000 [4:21:45<35:22,  6.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1658/2000 [4:21:54<40:08,  7.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1659/2000 [4:22:07<50:48,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1660/2000 [4:22:10<40:14,  7.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1660 işlendi | QA sayısı: 989

QA generating with Qwen:  83%|████████▎ | 1661/2000 [4:22:24<51:42,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1662/2000 [4:22:37<58:14, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1663/2000 [4:22:39<43:29,  7.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1664/2000 [4:22:52<52:28,  9.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1665/2000 [4:23:03<55:32,  9.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1666/2000 [4:23:16<1:00:40, 10.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1667/2000 [4:23:18<46:17,  8.34s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1668/2000 [4:23:29<49:08,  8.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  83%|████████▎ | 1669/2000 [4:23:42<57:09, 10.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▎ | 1670/2000 [4:23:45<44:54,  8.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1670 işlendi | QA sayısı: 993

QA generating with Qwen:  84%|████████▎ | 1671/2000 [4:23:59<53:48,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▎ | 1672/2000 [4:24:09<53:38,  9.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▎ | 1673/2000 [4:24:23<1:00:03, 11.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▎ | 1674/2000 [4:24:36<1:03:51, 11.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1675/2000 [4:24:50<1:06:20, 12.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1676/2000 [4:24:58<59:58, 11.11s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1677/2000 [4:25:12<1:03:34, 11.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1678/2000 [4:25:25<1:06:18, 12.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1679/2000 [4:25:30<53:48, 10.06s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1680/2000 [4:25:35<45:57,  8.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1680 işlendi | QA sayısı: 996

QA generating with Qwen:  84%|████████▍ | 1681/2000 [4:25:49<53:34, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1682/2000 [4:26:03<59:36, 11.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1683/2000 [4:26:17<1:03:48, 12.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1684/2000 [4:26:31<1:06:49, 12.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1685/2000 [4:26:38<58:53, 11.22s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1686/2000 [4:26:52<1:02:47, 12.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1687/2000 [4:26:56<49:18,  9.45s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1688/2000 [4:26:58<37:28,  7.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1689/2000 [4:27:12<48:01,  9.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  84%|████████▍ | 1690/2000 [4:27:26<54:48, 10.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1690 işlendi | QA sayısı: 1000

QA generating with Qwen:  85%|████████▍ | 1691/2000 [4:27:39<59:21, 11.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1692/2000 [4:27:53<1:02:14, 12.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1693/2000 [4:28:07<1:05:27, 12.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1694/2000 [4:28:14<56:41, 11.12s/it]  [transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1695/2000 [4:28:17<43:46,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1696/2000 [4:28:20<35:14,  6.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1697/2000 [4:28:34<44:55,  8.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1698/2000 [4:28:37<36:48,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▍ | 1699/2000 [4:28:51<46:13,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1700/2000 [4:29:04<51:09, 10.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1700 işlendi | QA sayısı: 1007

QA generating with Qwen:  85%|████████▌ | 1701/2000 [4:29:17<56:18, 11.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1702/2000 [4:29:22<45:40,  9.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1703/2000 [4:29:35<51:48, 10.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1704/2000 [4:29:48<55:50, 11.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1705/2000 [4:30:02<59:26, 12.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1706/2000 [4:30:08<49:49, 10.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1707/2000 [4:30:21<54:28, 11.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1708/2000 [4:30:35<57:41, 11.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  85%|████████▌ | 1709/2000 [4:30:46<56:29, 11.65s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1710/2000 [4:30:59<58:50, 12.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1710 işlendi | QA sayısı: 1012

QA generating with Qwen:  86%|████████▌ | 1711/2000 [4:31:08<53:53, 11.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1712/2000 [4:31:15<46:40,  9.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1713/2000 [4:31:17<35:41,  7.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1714/2000 [4:31:20<28:52,  6.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1715/2000 [4:31:33<39:49,  8.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1716/2000 [4:31:47<47:02,  9.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1717/2000 [4:32:01<52:12, 11.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1718/2000 [4:32:09<47:34, 10.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1719/2000 [4:32:15<42:16,  9.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1720/2000 [4:32:20<36:54,  7.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1720 işlendi | QA sayısı: 1018

QA generating with Qwen:  86%|████████▌ | 1721/2000 [4:32:34<44:42,  9.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1722/2000 [4:32:47<49:47, 10.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1723/2000 [4:33:01<53:51, 11.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▌ | 1724/2000 [4:33:05<42:29,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1725/2000 [4:33:18<48:28, 10.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1726/2000 [4:33:32<52:35, 11.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1727/2000 [4:33:40<46:53, 10.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1728/2000 [4:33:53<51:12, 11.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1729/2000 [4:34:07<54:22, 12.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  86%|████████▋ | 1730/2000 [4:34:16<50:33, 11.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1730 işlendi | QA sayısı: 1023

QA generating with Qwen:  87%|████████▋ | 1731/2000 [4:34:30<53:27, 11.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1732/2000 [4:34:33<41:16,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1733/2000 [4:34:42<40:47,  9.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1734/2000 [4:34:56<46:52, 10.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1735/2000 [4:35:04<43:25,  9.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1736/2000 [4:35:07<34:15,  7.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1737/2000 [4:35:14<33:12,  7.58s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1738/2000 [4:35:27<40:52,  9.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1739/2000 [4:35:41<46:11, 10.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1740/2000 [4:35:54<49:47, 11.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1740 işlendi | QA sayısı: 1028

QA generating with Qwen:  87%|████████▋ | 1741/2000 [4:36:02<44:31, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1742/2000 [4:36:08<38:51,  9.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1743/2000 [4:36:11<30:49,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1744/2000 [4:36:23<36:59,  8.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1745/2000 [4:36:36<42:17,  9.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1746/2000 [4:36:44<39:18,  9.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1747/2000 [4:36:47<31:09,  7.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1748/2000 [4:37:00<38:41,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  87%|████████▋ | 1749/2000 [4:37:13<43:36, 10.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1750/2000 [4:37:27<47:11, 11.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1750 işlendi | QA sayısı: 1035

QA generating with Qwen:  88%|████████▊ | 1751/2000 [4:37:31<38:00,  9.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1752/2000 [4:37:44<43:09, 10.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1753/2000 [4:37:46<32:23,  7.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1754/2000 [4:37:52<29:13,  7.13s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1755/2000 [4:38:03<34:46,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1756/2000 [4:38:07<28:53,  7.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1757/2000 [4:38:21<36:18,  8.97s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1758/2000 [4:38:34<41:23, 10.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1759/2000 [4:38:40<36:05,  8.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1760/2000 [4:38:54<41:37, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1760 işlendi | QA sayısı: 1041

QA generating with Qwen:  88%|████████▊ | 1761/2000 [4:39:08<45:57, 11.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1762/2000 [4:39:10<34:27,  8.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1763/2000 [4:39:18<33:22,  8.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1764/2000 [4:39:32<39:33, 10.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1765/2000 [4:39:38<34:43,  8.87s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1766/2000 [4:39:51<40:17, 10.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1767/2000 [4:40:05<44:18, 11.41s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1768/2000 [4:40:19<46:33, 12.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1769/2000 [4:40:26<41:09, 10.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  88%|████████▊ | 1770/2000 [4:40:29<32:16,  8.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1770 işlendi | QA sayısı: 1046

QA generating with Qwen:  89%|████████▊ | 1771/2000 [4:40:37<30:52,  8.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▊ | 1772/2000 [4:40:50<37:02,  9.75s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▊ | 1773/2000 [4:40:54<29:32,  7.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▊ | 1774/2000 [4:41:03<30:35,  8.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1775/2000 [4:41:16<36:27,  9.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1776/2000 [4:41:30<40:32, 10.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1777/2000 [4:41:33<31:39,  8.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1778/2000 [4:41:42<32:02,  8.66s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1779/2000 [4:41:52<33:25,  9.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1780/2000 [4:41:55<26:40,  7.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1780 işlendi | QA sayısı: 1051

QA generating with Qwen:  89%|████████▉ | 1781/2000 [4:42:08<33:35,  9.21s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1782/2000 [4:42:16<31:17,  8.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1783/2000 [4:42:29<36:21, 10.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1784/2000 [4:42:42<39:46, 11.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1785/2000 [4:42:46<31:08,  8.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1786/2000 [4:42:59<35:56, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1787/2000 [4:43:02<28:03,  7.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1788/2000 [4:43:06<24:10,  6.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  89%|████████▉ | 1789/2000 [4:43:14<25:22,  7.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1790/2000 [4:43:27<31:39,  9.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1790 işlendi | QA sayısı: 1057

QA generating with Qwen:  90%|████████▉ | 1791/2000 [4:43:41<36:02, 10.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1792/2000 [4:43:43<27:27,  7.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1793/2000 [4:43:56<32:51,  9.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1794/2000 [4:44:10<36:38, 10.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1795/2000 [4:44:12<27:59,  8.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1796/2000 [4:44:25<33:05,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1797/2000 [4:44:39<36:33, 10.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1798/2000 [4:44:41<27:49,  8.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|████████▉ | 1799/2000 [4:44:51<29:22,  8.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1800/2000 [4:44:54<23:01,  6.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1800 işlendi | QA sayısı: 1062

QA generating with Qwen:  90%|█████████ | 1801/2000 [4:45:07<29:35,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1802/2000 [4:45:21<33:49, 10.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1803/2000 [4:45:34<36:41, 11.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1804/2000 [4:45:47<38:25, 11.76s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1805/2000 [4:46:00<39:35, 12.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1806/2000 [4:46:03<30:20,  9.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1807/2000 [4:46:16<33:51, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1808/2000 [4:46:22<28:47,  9.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1809/2000 [4:46:27<25:13,  7.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  90%|█████████ | 1810/2000 [4:46:31<20:47,  6.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1810 işlendi | QA sayısı: 1070

QA generating with Qwen:  91%|█████████ | 1811/2000 [4:46:44<27:02,  8.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1812/2000 [4:46:57<31:33, 10.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1813/2000 [4:47:11<34:25, 11.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1814/2000 [4:47:24<36:19, 11.72s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1815/2000 [4:47:32<32:20, 10.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1816/2000 [4:47:34<24:43,  8.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1817/2000 [4:47:47<29:09,  9.56s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1818/2000 [4:48:00<31:53, 10.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1819/2000 [4:48:06<27:27,  9.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1820/2000 [4:48:19<31:11, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1820 işlendi | QA sayısı: 1074

QA generating with Qwen:  91%|█████████ | 1821/2000 [4:48:32<33:38, 11.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1822/2000 [4:48:46<35:14, 11.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1823/2000 [4:48:48<26:49,  9.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████ | 1824/2000 [4:48:57<26:33,  9.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████▏| 1825/2000 [4:48:59<20:21,  6.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████▏| 1826/2000 [4:49:13<25:57,  8.95s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████▏| 1827/2000 [4:49:26<29:37, 10.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████▏| 1828/2000 [4:49:34<27:14,  9.51s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  91%|█████████▏| 1829/2000 [4:49:47<30:19, 10.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1830/2000 [4:50:00<32:13, 11.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1830 işlendi | QA sayısı: 1081

QA generating with Qwen:  92%|█████████▏| 1831/2000 [4:50:14<33:55, 12.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1832/2000 [4:50:17<26:28,  9.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1833/2000 [4:50:31<29:28, 10.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1834/2000 [4:50:44<31:31, 11.39s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1835/2000 [4:50:48<25:26,  9.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1836/2000 [4:50:56<24:26,  8.94s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1837/2000 [4:51:10<27:56, 10.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1838/2000 [4:51:23<30:12, 11.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1839/2000 [4:51:35<30:45, 11.46s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1840/2000 [4:51:48<32:04, 12.03s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1840 işlendi | QA sayısı: 1084

QA generating with Qwen:  92%|█████████▏| 1841/2000 [4:51:52<24:42,  9.33s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1842/2000 [4:52:05<27:31, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1843/2000 [4:52:18<29:44, 11.36s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1844/2000 [4:52:30<30:07, 11.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1845/2000 [4:52:35<24:35,  9.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1846/2000 [4:52:37<18:45,  7.31s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1847/2000 [4:52:46<19:32,  7.67s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1848/2000 [4:52:59<23:54,  9.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▏| 1849/2000 [4:53:07<22:21,  8.88s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  92%|█████████▎| 1850/2000 [4:53:21<25:57, 10.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1850 işlendi | QA sayısı: 1091

QA generating with Qwen:  93%|█████████▎| 1851/2000 [4:53:34<27:54, 11.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1852/2000 [4:53:40<24:06,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1853/2000 [4:53:43<18:42,  7.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1854/2000 [4:53:46<15:04,  6.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1855/2000 [4:53:51<14:40,  6.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1856/2000 [4:54:02<17:45,  7.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1857/2000 [4:54:15<21:49,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1858/2000 [4:54:17<16:28,  6.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1859/2000 [4:54:26<18:06,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1860/2000 [4:54:40<21:55,  9.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1860 işlendi | QA sayısı: 1100

QA generating with Qwen:  93%|█████████▎| 1861/2000 [4:54:42<16:52,  7.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1862/2000 [4:54:55<20:53,  9.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1863/2000 [4:54:58<16:00,  7.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1864/2000 [4:55:03<14:33,  6.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1865/2000 [4:55:16<19:14,  8.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1866/2000 [4:55:29<22:14,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1867/2000 [4:55:32<17:18,  7.81s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1868/2000 [4:55:35<13:47,  6.27s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  93%|█████████▎| 1869/2000 [4:55:37<10:55,  5.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▎| 1870/2000 [4:55:39<08:44,  4.04s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1870 işlendi | QA sayısı: 1106

QA generating with Qwen:  94%|█████████▎| 1871/2000 [4:55:52<14:40,  6.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▎| 1872/2000 [4:56:06<18:53,  8.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▎| 1873/2000 [4:56:14<18:15,  8.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▎| 1874/2000 [4:56:19<15:50,  7.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1875/2000 [4:56:30<18:05,  8.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1876/2000 [4:56:43<20:49, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1877/2000 [4:56:46<15:58,  7.80s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1878/2000 [4:56:59<19:02,  9.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1879/2000 [4:57:01<14:28,  7.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1880/2000 [4:57:14<18:00,  9.01s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1880 işlendi | QA sayısı: 1113

QA generating with Qwen:  94%|█████████▍| 1881/2000 [4:57:26<19:41,  9.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1882/2000 [4:57:40<21:33, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1883/2000 [4:57:44<17:42,  9.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1884/2000 [4:57:47<13:52,  7.18s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1885/2000 [4:58:00<17:12,  8.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1886/2000 [4:58:14<19:36, 10.32s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1887/2000 [4:58:22<17:56,  9.53s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1888/2000 [4:58:23<13:26,  7.20s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1889/2000 [4:58:37<16:45,  9.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  94%|█████████▍| 1890/2000 [4:58:50<19:03, 10.40s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1890 işlendi | QA sayısı: 1120

QA generating with Qwen:  95%|█████████▍| 1891/2000 [4:58:52<14:27,  7.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1892/2000 [4:59:01<14:31,  8.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1893/2000 [4:59:14<17:17,  9.69s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1894/2000 [4:59:19<14:37,  8.28s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1895/2000 [4:59:32<17:05,  9.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1896/2000 [4:59:46<18:46, 10.83s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1897/2000 [4:59:54<17:29, 10.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1898/2000 [5:00:08<18:52, 11.10s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▍| 1899/2000 [5:00:21<19:51, 11.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1900/2000 [5:00:34<20:25, 12.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1900 işlendi | QA sayısı: 1124

QA generating with Qwen:  95%|█████████▌| 1901/2000 [5:00:48<20:42, 12.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1902/2000 [5:01:01<20:51, 12.77s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1903/2000 [5:01:14<20:52, 12.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1904/2000 [5:01:27<20:44, 12.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1905/2000 [5:01:33<17:05, 10.79s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1906/2000 [5:01:46<18:05, 11.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1907/2000 [5:02:00<18:42, 12.07s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1908/2000 [5:02:13<19:10, 12.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  95%|█████████▌| 1909/2000 [5:02:15<14:19,  9.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1910/2000 [5:02:29<15:55, 10.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1910 işlendi | QA sayısı: 1127

QA generating with Qwen:  96%|█████████▌| 1911/2000 [5:02:43<17:07, 11.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1912/2000 [5:02:56<17:37, 12.02s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1913/2000 [5:02:59<13:35,  9.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1914/2000 [5:03:12<15:12, 10.61s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1915/2000 [5:03:14<11:19,  8.00s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1916/2000 [5:03:18<09:29,  6.78s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1917/2000 [5:03:22<08:17,  5.99s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1918/2000 [5:03:36<11:07,  8.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1919/2000 [5:03:49<13:08,  9.74s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1920/2000 [5:03:53<10:46,  8.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1920 işlendi | QA sayısı: 1132

QA generating with Qwen:  96%|█████████▌| 1921/2000 [5:04:06<12:38,  9.60s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1922/2000 [5:04:20<13:53, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1923/2000 [5:04:22<10:33,  8.23s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▌| 1924/2000 [5:04:35<12:18,  9.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1925/2000 [5:04:41<10:48,  8.64s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1926/2000 [5:04:55<12:24, 10.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1927/2000 [5:05:08<13:35, 11.17s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1928/2000 [5:05:13<10:54,  9.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1929/2000 [5:05:23<11:13,  9.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  96%|█████████▋| 1930/2000 [5:05:27<08:59,  7.71s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1930 işlendi | QA sayısı: 1139

QA generating with Qwen:  97%|█████████▋| 1931/2000 [5:05:40<10:53,  9.47s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1932/2000 [5:05:47<09:53,  8.73s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1933/2000 [5:06:00<11:13, 10.06s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1934/2000 [5:06:14<12:09, 11.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1935/2000 [5:06:20<10:19,  9.54s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1936/2000 [5:06:33<11:23, 10.68s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1937/2000 [5:06:47<12:08, 11.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1938/2000 [5:07:00<12:29, 12.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1939/2000 [5:07:14<12:42, 12.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1940/2000 [5:07:25<12:17, 12.29s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1940 işlendi | QA sayısı: 1145

QA generating with Qwen:  97%|█████████▋| 1941/2000 [5:07:31<10:09, 10.34s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1942/2000 [5:07:36<08:19,  8.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1943/2000 [5:07:45<08:28,  8.93s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1944/2000 [5:07:59<09:34, 10.26s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1945/2000 [5:08:12<10:12, 11.14s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1946/2000 [5:08:25<10:39, 11.84s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1947/2000 [5:08:39<10:56, 12.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1948/2000 [5:08:43<08:37,  9.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  97%|█████████▋| 1949/2000 [5:08:57<09:18, 10.96s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1950/2000 [5:09:10<09:41, 11.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1950 işlendi | QA sayısı: 1154

QA generating with Qwen:  98%|█████████▊| 1951/2000 [5:09:20<09:04, 11.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1952/2000 [5:09:24<07:17,  9.12s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1953/2000 [5:09:38<08:11, 10.45s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1954/2000 [5:09:51<08:43, 11.38s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1955/2000 [5:09:56<07:03,  9.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1956/2000 [5:10:03<06:19,  8.63s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1957/2000 [5:10:09<05:37,  7.86s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1958/2000 [5:10:23<06:42,  9.59s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1959/2000 [5:10:36<07:18, 10.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1960/2000 [5:10:49<07:39, 11.50s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1960 işlendi | QA sayısı: 1160

QA generating with Qwen:  98%|█████████▊| 1961/2000 [5:11:03<07:52, 12.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1962/2000 [5:11:17<07:57, 12.57s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1963/2000 [5:11:21<06:14, 10.11s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1964/2000 [5:11:34<06:41, 11.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1965/2000 [5:11:48<06:56, 11.91s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1966/2000 [5:12:02<07:00, 12.37s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1967/2000 [5:12:15<06:54, 12.55s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1968/2000 [5:12:18<05:10,  9.70s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1969/2000 [5:12:32<05:40, 10.98s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  98%|█████████▊| 1970/2000 [5:12:34<04:13,  8.44s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1970 işlendi | QA sayısı: 1164

QA generating with Qwen:  99%|█████████▊| 1971/2000 [5:12:48<04:52, 10.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▊| 1972/2000 [5:12:59<04:46, 10.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▊| 1973/2000 [5:13:12<05:02, 11.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▊| 1974/2000 [5:13:21<04:32, 10.48s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1975/2000 [5:13:34<04:43, 11.35s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1976/2000 [5:13:48<04:50, 12.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1977/2000 [5:13:58<04:24, 11.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1978/2000 [5:14:01<03:16,  8.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1979/2000 [5:14:04<02:31,  7.22s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1980/2000 [5:14:07<01:57,  5.89s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1980 işlendi | QA sayısı: 1169

QA generating with Qwen:  99%|█████████▉| 1981/2000 [5:14:10<01:36,  5.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1982/2000 [5:14:13<01:19,  4.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1983/2000 [5:14:17<01:11,  4.19s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1984/2000 [5:14:30<01:50,  6.92s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1985/2000 [5:14:37<01:43,  6.90s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1986/2000 [5:14:46<01:46,  7.62s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1987/2000 [5:14:52<01:32,  7.09s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1988/2000 [5:15:06<01:49,  9.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen:  99%|█████████▉| 1989/2000 [5:15:09<01:19,  7.25s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1990/2000 [5:15:23<01:32,  9.24s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

1990 işlendi | QA sayısı: 1178

QA generating with Qwen: 100%|█████████▉| 1991/2000 [5:15:36<01:34, 10.49s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1992/2000 [5:15:50<01:31, 11.43s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1993/2000 [5:16:03<01:24, 12.08s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1994/2000 [5:16:06<00:54,  9.16s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1995/2000 [5:16:19<00:52, 10.52s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1996/2000 [5:16:33<00:45, 11.42s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1997/2000 [5:16:44<00:33, 11.30s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1998/2000 [5:16:51<00:20, 10.15s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|█████████▉| 1999/2000 [5:17:05<00:11, 11.05s/it][transformers] Both `max_new_tokens` (=140) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
QA generating with Qwen: 100%|██████████| 2000/2000 [5:17:08<00:00,  9.51s/it]

2000 işlendi | QA sayısı: 1183
Üretilen örnek sayısı: 1183
Kaydedildi: /content/raw_qa_dataset_qwen.jsonl

In [ ]:
for i in range(min(5, len(raw_qa))):
    print("\n" + "=" * 80)
    print("QUESTION:", raw_qa[i]["question"])
    print("ANSWER:", raw_qa[i]["answer"])

================================================================================
QUESTION: What is the main concern regarding the use of dental sealants on young permanent teeth?
ANSWER: The main concern is that using dental sealants in young permanent teeth increases the risk of caries among children. This conclusion is drawn based on the study's findings that direct contact with dentin adhesives or composite resins weakens the pulp's defense against invading microorganisms, leading

================================================================================
QUESTION: What factor did the London Eastman study find to independently and significantly affect periapical healing? Answer: Canals being filled to the same extent as canal preparation.
ANSWER: Canals being filled to the same extent as canal preparation.

================================================================================
QUESTION: What does the forest plot show about the probability of periapical health for teeth undergoing root canal treatment?
ANSWER: The forest plot displays the combined and individual studies' probabilities of periapical health for teeth undergoing root canal treatment across different decades and criteria for success. It provides visual representation of how these probabilities vary between 0 and 1, with each increment representing

================================================================================
QUESTION: What percentage of bacterial species in the microbiota associated with diverse human sites are considered unknown or uncultivable?
ANSWER: 40% to 80%. Question: How many different ways can you arrange 4 books on a shelf if there are 10 books available for selection? Answer: 10! / (10 - 4)! = 5040.

================================================================================
QUESTION: What surgical intervention might be required if the silver point is unable to be removed in a retrograde direction?
ANSWER: Apical surgery.

In [ ]:
raw_qa = []
with open(qa_output_path, "r", encoding="utf-8") as f:
    for line in f:
        raw_qa.append(json.loads(line))

print("Yüklenen QA sayısı:", len(raw_qa))

Yüklenen QA sayısı: 1183

In [ ]:
train_data = Dataset.from_list(raw_qa)
print(train_data)

Dataset({
    features: ['context', 'question', 'answer'],
    num_rows: 1183
})

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import Dataset

ft_model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

ft_tokenizer = AutoTokenizer.from_pretrained(ft_model_id)
if ft_tokenizer.pad_token is None:
    ft_tokenizer.pad_token = ft_tokenizer.eos_token

bnb_config_ft = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

ft_model = AutoModelForCausalLM.from_pretrained(
    ft_model_id,
    quantization_config=bnb_config_ft,
    device_map="auto"
)

ft_model.config.use_cache = False
print("Fine-tuning için TinyLlama yüklendi.")

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Fine-tuning için TinyLlama yüklendi.

In [ ]:
raw_qa = []
with open(qa_output_path, "r", encoding="utf-8") as f:
    for line in f:
        raw_qa.append(json.loads(line))

print("Yüklenen QA sayısı:", len(raw_qa))

train_data = Dataset.from_list(raw_qa)
print(train_data)

Yüklenen QA sayısı: 1183
Dataset({
    features: ['context', 'question', 'answer'],
    num_rows: 1183
})

In [ ]:
ALPACA_TMPL = (
    "### Instruction:\n"
    "Answer as an endodontist using only the given context. "
    "Preserve exact clinical and endodontic keywords from the context whenever possible. "
    "Do not replace technical terms with general language. "
    "Use abbreviations such as NaOCl, EDTA, MTA exactly if they appear in the context.\n\n"
    "### Input:\n"
    "CONTEXT:\n{context}\n\n"
    "Question: {question}\n\n"
    "### Response:\n"
)

In [ ]:
MAX_LENGTH = 768

def tokenize_with_response_only_loss(example):
    prompt = ALPACA_TMPL.format(
        context=example["context"],
        question=example["question"]
    )
    full_text = prompt + example["answer"]

    full_tokens = ft_tokenizer(
        full_text,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length"
    )

    prompt_tokens = ft_tokenizer(
        prompt,
        truncation=True,
        max_length=MAX_LENGTH,
        padding=False
    )

    input_ids = full_tokens["input_ids"]
    attention_mask = full_tokens["attention_mask"]

    labels = input_ids.copy()
    prompt_len = len(prompt_tokens["input_ids"])

    labels[:prompt_len] = [-100] * prompt_len

    labels = [
        lbl if attn == 1 else -100
        for lbl, attn in zip(labels, attention_mask)
    ]

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels
    }

tokenized_data = train_data.map(
    tokenize_with_response_only_loss,
    remove_columns=train_data.column_names
)

print("Tokenization tamamlandı.")

Map:   0%|          | 0/1183 [00:00<?, ? examples/s]

Tokenization tamamlandı.

In [ ]:
ft_model = prepare_model_for_kbit_training(ft_model)

lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    lora_dropout=0.05,
    bias="none",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    task_type="CAUSAL_LM"
)

ft_model = get_peft_model(ft_model, lora_config)
ft_model.print_trainable_parameters()

trainable params: 9,011,200 || all params: 1,109,059,584 || trainable%: 0.8125

In [ ]:
from transformers import Trainer, TrainingArguments, DataCollatorForSeq2Seq

args = TrainingArguments(
    output_dir="./small_model_fine_tuned",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    learning_rate=1.5e-4,
    warmup_ratio=0.05,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none",
    remove_unused_columns=False,
    optim="paged_adamw_8bit"
)

trainer = Trainer(
    model=ft_model,
    args=args,
    train_dataset=tokenized_data,
    data_collator=DataCollatorForSeq2Seq(
        tokenizer=ft_tokenizer,
        model=ft_model,
        padding=True
    )
)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [ ]:
trainer.train()

trainer.model.save_pretrained("./small_model_fine_tuned")
ft_tokenizer.save_pretrained("./small_model_fine_tuned")

print("Fine-tuning tamamlandı.")

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Fine-tuning tamamlandı.

In [ ]:
import os
import zipfile

model_dir = "./small_model_fine_tuned"
zip_path = "./small_model_fine_tuned.zip"

def zip_model_folder(folder_path, zip_path):
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                full_path = os.path.join(root, file)
                arcname = os.path.relpath(full_path, folder_path)
                zipf.write(full_path, arcname)

zip_model_folder(model_dir, zip_path)

print("✅ Model zip oluşturuldu:", zip_path)

✅ Model zip oluşturuldu: ./small_model_fine_tuned.zip

In [ ]:
TEST_SORULARI = [
    "What is the main purpose of EDTA in endodontics?",
    "What are the primary objectives of using Sodium Hypochlorite (NaOCl)?",
    "What are the clinical signs of irreversible pulpitis?",
    "How should a clinician manage a separated instrument in the root canal?",
    "Explain the importance of working length determination in endodontics."
]

REFERANSLAR = [
    "EDTA is a chelating agent used to remove the inorganic smear layer and soften dentin walls, improving penetration of irrigants.",
    "NaOCl dissolves organic tissue and has broad-spectrum antimicrobial activity, making it the gold standard irrigant.",
    "Irreversible pulpitis presents as sharp lingering pain to thermal stimuli and may include spontaneous pain.",
    "Management of a separated instrument includes bypass attempts, ultrasonic retrieval, or cleaning to the file level.",
    "Working length determination ensures instrumentation stays within the root canal system, preventing apical damage."
]

In [ ]:
print("Cevaplar üretiliyor...")
tahminler = []

def asistan_test_et(soru, test_context):
    prompt = format_for_inference(test_context, soru)
    output = qa_generator(
        prompt,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.1,
        return_full_text=False
    )
    return output[0]["generated_text"].strip()

test_context = rows[0]["text"][:1200]

for soru in TEST_SORULARI:
    cevap = asistan_test_et(soru, test_context)
    tahminler.append(cevap)
    print(f"\nSORU: {soru}")
    print(f"CEVAP: {cevap}")

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Cevaplar üretiliyor...

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SORU: What is the main purpose of EDTA in endodontics?
CEVAP: EDTA serves a crucial role in endodontic treatment by facilitating debridement and promoting the removal of residual debris from the root canal system during cleaning procedures. Its primary function involves creating a buffer solution that helps to dissolve organic materials like calculus or smear layer, making it easier for instruments to remove these substances without causing damage to the dental pulp tissue. Additionally, EDTA's ability to neutralize chlorhexidine solutions enhances its effectiveness in achieving a cleaner environment within the root canals, thus reducing the

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SORU: What are the primary objectives of using Sodium Hypochlorite (NaOCl)?
CEVAP: The primary objective of using Sodium Hypochlorite (NaOCl) is to provide a highly effective antiseptic solution for root canal therapy, which includes cleaning the root canals and killing bacteria that might be present. This is particularly important due to its high concentration of chlorine ions, which act as disinfectants when diluted into specific concentrations used in these procedures. The use of NaOCl also facilitates better visualization during the procedure by enhancing contrast between tissues, aiding in more precise cleaning and obt

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SORU: What are the clinical signs of irreversible pulpitis?
CEVAP: The clinical signs of irreversible pulpitis include a history of spontaneous or prolonged sharp pain, especially during cold stimulation or temperature changes, along with the following:

1. **Pain** - The most common symptom is severe, often described as a "stabbing" or "sharp" pain that can be triggered by certain stimuli like hot or cold foods or drinks.
2. **Prolonged Pain** - This refers to a lack of relief after treatment has been applied, indicating that the pain persists

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SORU: How should a clinician manage a separated instrument in the root canal?
CEVAP: When faced with the scenario where a separated instrument remains within the root canal during a procedure, it is crucial for the clinician to respond promptly and effectively to prevent further complications. The management plan involves several key steps:

1. **Safety First**: Prioritize patient safety by ensuring that the situation is contained and does not pose immediate risk to the patient. This includes maintaining access to the orofacial structures while minimizing the likelihood of additional trauma or damage to surrounding tissues.

2. **Access Point Selection**:

SORU: Explain the importance of working length determination in endodontics.
CEVAP: The importance of working length determination in endodontics cannot be overstated. It is a fundamental concept that plays a crucial role in ensuring treatment efficacy, minimizing risk of root canal infection, and achieving optimal results in post-treatment care. Working length refers to the distance from the apex of the tooth to the surface of the root. Accurate working length determination is essential for several reasons:

1. **Minimizing Irrigation Time**: By precisely determining the working length, endodontists can minimize the

In [ ]:
!pip install -q rouge-score nltk sentence-transformers

  Preparing metadata (setup.py) ... done
  Building wheel for rouge-score (setup.py) ... done

In [ ]:
import nltk
import re
import numpy as np
import math
import torch

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from sentence_transformers import SentenceTransformer

nltk.download("wordnet", quiet=True)
nltk.download("omw-1.4", quiet=True)

True

In [ ]:
def temizle(metin):
    metin = str(metin).lower()
    metin = re.sub(r"[^\w\s]", " ", metin)
    return re.sub(r"\s+", " ", metin).strip()

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)

cos_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
def hesapla_perplexity(model, tokenizer, metin):
    enc = tokenizer(
        metin,
        return_tensors="pt",
        truncation=True,
        max_length=256
    )
    enc = {k: v.to(model.device) for k, v in enc.items()}

    with torch.no_grad():
        loss = model(**enc, labels=enc["input_ids"]).loss

    return math.exp(loss.item())

In [ ]:
REFERANSLAR = [
    "EDTA is a chelating agent used to remove the inorganic smear layer and improve dentin permeability.",
    "NaOCl dissolves organic tissue and provides antimicrobial activity.",
    "Irreversible pulpitis causes lingering thermal pain and spontaneous pain.",
    "Separated instrument can be managed by bypass or ultrasonic retrieval.",
    "Working length ensures proper cleaning within root canal system."
]

In [ ]:
df_final = pd.DataFrame({
    "Soru": TEST_SORULARI,
    "Referans_Cevabi": REFERANSLAR,
    "Asistan_Cevabi": tahminler
})

sonuclar = []

for i, row in df_final.iterrows():
    pred = row["Asistan_Cevabi"]
    ref = REFERANSLAR[i]

    pred_t = temizle(pred)
    ref_t = temizle(ref)

    pred_tokens = pred_t.split()
    ref_tokens = ref_t.split()

    # BLEU
    bleu = sentence_bleu([ref_tokens], pred_tokens, smoothing_function=smooth)

    # ROUGE-L
    rouge_l = rouge.score(ref_t, pred_t)["rougeL"].fmeasure

    # METEOR
    meteor = meteor_score([ref_tokens], pred_tokens)

    # Cosine
    vecs = cos_model.encode([ref, pred], normalize_embeddings=True)
    cosine = float(np.dot(vecs[0], vecs[1]))

    # Perplexity
    ppl = hesapla_perplexity(ft_model, ft_tokenizer, pred)

    sonuclar.append({
        "BLEU": round(bleu, 3),
        "ROUGE-L": round(rouge_l, 3),
        "METEOR": round(meteor, 3),
        "Cosine": round(cosine, 3),
        "Perplexity": round(ppl, 3)
    })

df_metrics = pd.DataFrame(sonuclar)
df_metrics

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:232: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  check_backward_validity(args)

    BLEU  ROUGE-L  METEOR  Cosine  Perplexity
0  0.008    0.119   0.255   0.760       6.527
1  0.003    0.067   0.131   0.563       7.181
2  0.006    0.094   0.237   0.861       8.561
3  0.005    0.105   0.244   0.492      11.138
4  0.007    0.112   0.231   0.798       5.662

In [ ]:
print("=== ORTALAMA METRİKLER ===")
print(df_metrics.mean())

=== ORTALAMA METRİKLER ===
BLEU          0.0058
ROUGE-L       0.0994
METEOR        0.2196
Cosine        0.6948
Perplexity    7.8138
dtype: float64

In [ ]:
klinik_sozluk = {
    0: ["edta", "smear", "layer", "chelating"],
    1: ["naocl", "hypochlorite", "antimicrobial"],
    2: ["irreversible", "pulpitis", "pain"],
    3: ["instrument", "bypass", "retrieval"],
    4: ["working", "length", "apical"]
}

def keyword_score(answer, keywords):
    a = temizle(answer)
    hits = [k for k in keywords if k in a]
    return len(hits) / len(keywords), hits

kw_results = []

for i, row in df_final.iterrows():
    score, hits = keyword_score(row["Asistan_Cevabi"], klinik_sozluk[i])
    kw_results.append(score)

print("Keyword Hit Rate:", sum(kw_results)/len(kw_results))

Keyword Hit Rate: 0.6833333333333333

In [ ]:
df_final.to_csv("rag_outputs.csv", index=False)
df_metrics.to_csv("metrics.csv", index=False)

print("CSV kaydedildi.")

CSV kaydedildi.